---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgBT8t9gcwZQKShwdaYActLnzn0tIKHfYfuxWey/kLcqhADa2wOQuHI7kBZRHzHGfhZrwidfiT+kJ4diTGiWaFgN1tpQPxZftE1ItT5yjnOs48Eyfi8UR3kssYkv3CI5ee1xcCTlSYdDBNpkjtMHW6WM7uEXkWrfdbHSwgHdJHjuV9vwTXFn+WldwOwthPqzQXNy+q4cdqSxXJQFd37lV6xNxZeqg3c8ZOrz8kihlHHV2Pq+WxAzs0F5n3eXB+2Upo313CBpgZXYGo0hXh9upwQ16OAbdezPwVO2rWnybqZ0MxauoXOAe8R49l3LSIBnOq1oCMzEQBzJp6bwTdE1f2RgGZXJ0Wc0xw+iyXuFuqx4pa8q83hA0r5sOFUAlRid97kvndPiT+vLuCBnNpceXBHOiuGsZZH2fQX/eFQ2qadO5w4NKkwFEootiY6/Jytka24cZMZD5iyEYqrVJaDZ/Wj5HD/s7XhEaOVr0HFV6CxiRDkEdEhuNjnrX0d7vAH21WeuUjVr80RYZbiSyMmvcxrtO9YOUlccHE6L7JVk3tpwjia/2edMyNSQYdYfj9GyAPA17ezmp3bx2KMYmIJbiiS+2D5Ap5TCTCq5KIX/CyCV7sdjjELke2EIXpZ4aadd/qcJtVnYjDQJ0Q0RQybzAenRrexJ5Pexza0F9Mp4DL+xNXf/bVxzjDHGtZ+nlPixUvi+m0PVVxqwskzw6OVURM4Hv2rgVZE9L9JlfCElOhbyf6Yu0P8nvX0sRS82wVDjkxNsjg2IPLsUfbcQLTM=
    username: AgDJxlIHCaYIZIspL4XalD5MKjVPEZk3syElcTtwSKBYh/W49BixmmMGC/Yh24jBSLVGxc960P8+QrAsXtemk06A5lC920zWQZAwp4qkMzRnN0DJUZdU3SAqNRtS2ZsVHtUX5UANchUDfaqwsc3fY/vg3nQ/1BuYkepRzdMssz2clnIcAvFxGIyMOmGhTZgz02G78FY9ZkVMCYDKSp7r+SiUtZ6dUfpn7YLoqTe0EQQKTPN+vYO8TrNXkA8QUli5+1GmBf8SZwpx5OKrIJXkjdF+uZuvhuhK771ZThY95S8I5AWR4AO9nPoZn20u87AkrTK8AKBzKULQv2XaCXzljodYkqGWuhdvXpqazyUQFdhC3m3f3Xwnwfdip2cfgP5tV3LEOTiIH6TShDgtM+G30u8NmSDHy09OMkJbKXSvFlvB7I/LzEBaM6q0NVobirZYUQ0OHUg1m9YhSrVE02sSMLi1OlNAafmEla/nccd2X8AsNs5gxd+BSAFhtUUgcd5jTNQlS65g4zi85eIPx0BFCE5+g0R28F7X4WHFWI4kmOjj9BLmQY2DQ9g0skeo9GQ4NEpz+PsaLVhcitGaYpS6LkOLe7kU4z1ZkNbqjKKJ3mkLXwsIkQFOJSHskPiN15ioI89mXcl641pgsq1kqD+4A1yUTByfMiL7OmOKWNFnk7YD7YBFGW/8O13AGWbQ8fnSxIdnrwMx6Q==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
