---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgB5sCbaWxzM4juZTOWOtGzigoLYPCM3VoIpyTZm0yd+w5tkwtWR8O3ppmwAt1h4+QInYgw6CWBQ9cJFw7nWc3qu9AQ9tahAaFld1ST8/llP/aKStgDmE8UgSDYyYt0K76wDvRtCmTjySUdUs0IAe5V1XoxB6pAPWrnBe8YInbHy1/z6LLl8+BUspX0BpHAsX4Mx2Mak+Hr4Iv+Pu/9aJHQRrhZfs0EjWLu/R0ZjqqTYL17qPQ0cC8OrrY+rlGwyf8G5aEbktvBxs9GV5TzDINYy3G+ONiHPpxA4kAKew6KNgSoDt7oK8PgmOCfGAJNMaFCshvVMBfyZwxGCoKOGRSpeHJUtNE/X/DukcJhr7YjGCPX0IkHBzQZvLHLDqdoFTvPNA+UE8lc4GjFJQsfziKsxUPOVYzSlTy6Kj5+hgZxA3FOimj0q/3WsxlfGM55M6nRmcVos4OQPHrxhelQKIDd3AN08MgpDpnUQsEVgBkWINPgmEImwrT8aud0djzEjPsIgIV2IHSgy1nnJuMnAGyYDXkkCQ9rmK4e4O0z5JCZUO8qc6zRJaaubCrfj8POnMRqR5L3/31ZupYPA2FXMXlPt9+ZWAhPRzQV3PhTMsBbgDr9mRIgLf33VAlEl2u4o4QaTpO03HFa2wxYaG7s4tDWFl+yqwi1Ia4tPhWgaxpsTd6hSM0p48qfgXmMP4pfqcE/jTILXQTb+iY+MzKaAWBIQqi2VTLqWywdqVyCQGBYARw==
    username: AgACL1Upex0TZEPKmL+I5ChlwcXXq6lNrZVhshO4gHtPcrNxmxeGOkirMm51MwJTmJ1h9mTjwY35tiBWku3qorKJzN3y8vOpC40kAcyaP3FjvB1eO52xQJ2BTlIAQp3/a6utRyo+3iAH30QANVP5986zU1pe6ZY89rhCNd/4bnL1rY+9LHl1XmgU8w5FHnpEAGgh7qmyx6CAd8CxHW9vM4cjwS+YnGpTo1OoJ53t2ckggKcg1QlQ13wPKMNrynjm2rade+yEgp+oiB2GQxn8yf8RTFDYTMjXnK+mKc+HxI6Ne/SXOyo4+zVyjYje0Lf8YGSM2NSxiGMGdegPvqHb1zaLapL6H/j1WykGERCLZTOoEmXSyTWthqUCpriCIBO4COYGXKeI78AbRT8RlKf3lsyuwZwRkJM8th1xoBirikJDoSmNKsTdKBFgRwh2KYPZzVEUufQLQM8uqCX9IhmPqJOCi6h9gnxQG2Zf/iMwAnnimr2DB6a4aTM+M692Gb/nf0ijz+o2HJv21yEncbu2Ubdk8/5eEmHeIVBQ/HJJqbgQ6wEbRvNcLgPy58PZEOZOco4N3r7+gD3Ltei6Jm4EhA9LfgRXR7USr2JOCb/QC9gycfr/pvCM+ACjdZb0OPG2s4LMzTRACPmMXgr7iWKTuA7vgk/wwMRfR+XJ2z2/cvOfpm4aTLzMAEfhmcQ97zSvjHyaGpbmDw==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
