---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCub0B7/bW5B5ZPJIkRKXjkRbxbJkKrXWZxmMDWOUDF1cEvpFmMbsmPTi2VOWg/r6sYPZOEYQ4+nqqkLt5Z+ipA50OY2Nv5tgWQxJNrtdUyV0/aBxhKnXd2wG1GtwwHUG6ogBGrUHbc4W/e9SkQBlgFCKWtyTNKiYydfQ2d/00T3JMRaHMiNFBbFmu3LbAeFdPVo0SXzAO+b8npXV5LZ9JfTHsfnlmOfpJ+GbPQB51T32ZgRjmo7xjHTv/jVAnzaBRrOTrSr8ESFOwr7buNSuOpcifQiBf3Q6EI7Koqr1soCDsgtSjHeEMtVuuQZNDtK3+ATIxPPks5haRDo3mhRSOn4shwxq5PF3RB27uiMA5wUY34R4ciYg8pMsxNr7eiY+QkRfnc1wd6TyYiN3J6pdPEBS7OMeYZRxr1eal2MsQq5o8GcQiUTdc5vyPY6T5V9tir+X5Kv/Q+a+d3o6cXQgdmv9D177ythy9LovFPhWzRSM30/bmQp3QlU6W0Pdsvnf1rqMcopow6oT7V3co3c9NCg0icgFlLsVZ+yPtr7rSliLiThViLqqI/r/VLUyx1+/YlM01iZWX6NoOzAKhuRHf7MePJ0jK2FJ/j861E3XLCghQAGWnT4DPGx4kufVzWtlmmmswTcj+ftLMyTiTrznOwhmhMiITOg+zDXx+8NrGz8BdPT2Lui0brWEDqGiCvbO1lZzeZL+gXfFBeyTJtVLWtphyYI6c3CEoLQvkKq33grA==
    username: AgCu/zdwHJsGnn7YuD50u4ZibeUboJNVCSfJ5qj0SDLj1ZWWkiNCCoUU6aCm3eHKEmZ9pRQ9Kdj134uLQdxNXJQlGAvGRmI1UuTc/ohzm63IKNbPO93ZSfqtsWejxhSQhd5LxmwIl3/QKWTt0YWUB5+tw5n3m7Ag4hVlJf15AJEtSG5bkXPJXXuMt4tg2Rlsa/a8BUruyT/UjFIff+hSdzoSmeWbhCtDBbGuXRpSF0kERYssrCc9ykAlDNBWILj0T/+hXIn86MRg0MOBKKA9Ew2nuK+KgXD22WaxkyuCA87yUC8ZqMpTITL1k9SYD8ru/XBTvqhB9YVfr9Zj+2X+flHab5DsWE+AsY5GdFLxpGx6NKOY3ktbxZ3yjwVMRUiyv8YBaKg8pg5LfPTk31DbIP98bSwFFTjUVcqNCBmYFDmgwR8Ms5pvT3uLqECqJEhOShAUMsigHzVAMaTBgdF8cXDU6fRwwuO37kTMVi3RYmehRsSaMasr1Z57k9+WzsMADghDvhLaqAsM7aenDf157LqhnGa6sFAoPtFq7jFUFWwclQxY+W2lO9IVMsPnCGuYFPPD6gTcmJp9d/sp+gzuOkWLexiFafFABXBbubSBeF7MweWzhxWw/xxnbmr6FcgMzX3up4iOE8B5yTGr5bZOF9JT4mvlhL34Ie8fuLLAwqxLBjNsUkklfjvhO+s/xtyzyZA8SzFmEw==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
