---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgBOezb0CcrPJCK94T98KE5I/W1BR7wRBVpTlAeVH1w9sEyw7mWUZUdiEejAiTXvbHtuvb5mnOPVBQjMZ7AP6X9Tge1D0sbA8ZV40tmAPws2OaaV97Z51PjvOLGWj9t37HW+42o+qiuzMfMpBb7PV/h/8JKg5SY/qZqYSyGXaiVp/uDx3e0cUz++C+KDBB3eofBKmf1kT0hBxFAGR/kPwE5oOadmIIUZb/Sz46AvJW/SJmM6KzsoIA+ccuZ+nQDeNxjbf7XsS9/vmsHGT1qa22MflIt6DJ4Heo31lffwJyfSKSFHPQ0p1jKuR3UpTHNIU0OCUicq4HGEulp9lY5Ws64dnT79Ffnvyownl2CRWY6hY7KAF+wH0xH+YhQ6O0CF+mpk08LunL0pKD7ACgaCEH4FBX5dRr0pajiyJP5Froyn8mnODChjrkzeyW27+coXTQ8STGPm+8bKVUQVr/eU4M2Nj7E3UiRfPFpW4a4m4bRkzknI9/4aZwfvXKCQC2KO3/+04LZaqfLM9FMWNbrLpX1x/Zaq1HTfGARwfGihyaljtpT9W1NKbW4fuY7Zr8ORHeFQrM9Quj/P4x16bEeklQFQIEzX4tyXLk2URnwWN5oZBYnMmXIT8Fox8RSq6RimNIMwQRHLS4OK379auJTCx379eS+4kLB1IPwfpCyWXuXxT025BeUy+WDWTdJrRjYsU0cp/IgRy/V1a41f/pPTGivggM8UTTaUnEQoM0eQ67GyDgsvZiPYhMdhDeCjerD8JG1TIEBCN3cfiPX9DLM=
    username: AgCdyuf7ZgHgDEkeijCl+uYHg5+kZ/FrnD+7atJ6TAni0/Il9u/U3/lyVND2VTdYQcjhRUyZZPbtXSa7I3uMGgnjBNMErVDNIezYbdOKKDLGPZEXlG6Fxg3i4VrxqaSuAWSfIg6aY4pUiuBJueGX1gklPi0z9d/gcm1MFF9xjJnZX1aMbdCFdqgCa8cpB74YAKFPUFHjuQ5abUlEy2WNvw6wcwpAH2rS9KGASCupsuRzw/ru/H4UGMag07PiLFrUyjvaL5cYiAOINelkN6QImKefoCk1JNzJL9JudaxIfOi91TU8zPk497Q3qs3BI9+tOOyyBSZ6vjfq2ZtOl2gAsgvYdt5GtJoMLeGh7jH50g2CCKVKjNNkT0lTwtNyaK5zHhtOo19HGSRlkgOWlrfOwAomHXoaQ43BIEop2a4+1lyw4Fbx953rC1rk8lhAzPXNpMJTO2HMXM6tTQc9k1v+2Yly0WuQ7SJprdhBrgn2Rjppfr9BgupA0VKirZPi0qh9AGC2oBsdl+om75nEiZVz9ynrOP1nkAFDnCb2ykYWBTONB0Wdo8fe17TD50BTq197Bs3HD1K+NWbKt7nm8ZBvr7VdUBeDfrp+8X2jdJAqvXEPpgTJ4Crul8OaRwqnjyfa1WjyH4zOxQuxAhZX+AYl0SnCEI5jZlNaY6zx5nUiXtX7QbTI/H3P8V83SDJjBY8hcyhXAQBLcw==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
