---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgBlUeuJrqXSl6z8jdD0k+EcWoewuSKp2l3m1XL5XnxU6k6Jn33SstWyAhq/+Z6KgWTHdt628BTjPxsWnNhBaJxD1PopGCuzVzz3vN/MwjQIc2e4HuZ3v66d4gQzXekS/vmWwzxd0hencsgLs+ccSQ9MqX+0DFVwJ/PpPG/Rz2cdfv8aoK7iaTOtjGs0RrgJUUD7Z+wxT3AYaR77m07aqZjmmPN+zMIIgq4Tt8Tr1out31Ooqw3wM1SrUBf94jItx97OIGYN9SIrjR97ZplMU/lc8Q1Z2J8CEMIKlA+g0yo2qTpsQd3r6Iv2JailaWLJ/aN4h0Nht3gmd1a1qeCK26kNYL3eZBm8wElX7+Hutm8b09/aJNgvytHNk/FB/+AFDIqL4kdkQ4gNunkI5hje301cUD3BSj6Nw2/Sa2t7aX+ECTPheMzkqP3vY16ZRBQvxhKCgatFw0uVTGkEYf3+oIULcyRTOCv1qF30XMRwHQXP/dhsmBSZJ4X8saPPgBfISPvjb27TOw5sn5egV7i7eU98qJlyIFz9oq8Mack6EHuU3KHI3BKBzh9eMfLWRzYvIaC6vkiktx+16fbIg3fFegdkiumgPydUhAln3AgHfXboaDpyhlWsoD1f4FzsWISAjFTte8XCuUiHCQ/t2c+EtM7bIkvByGxKVi8Yb2QnaveBFNGyqOPUaRqpddcIj/Bp7TN/kUoavfxtH8SzEe7/8mP5uqRJXpUZVO/0zrUX9uQXCA==
    username: AgCAzV5zP3noJRifZUiSQ1fDqdWFojiKCOmbxhjHviq0s0O+EdXztdeFlz/WQUwCySxfWbKYmkerOhFPWjKu1ZfhmHJ7w87HngFN+b6lYjcrTJBXBt668sgCm0eMFyntlJ0k3MlcioZiNpS4yLafVgu2ssX2aJ84N8d49scf1TT5ckz1I2aEOv2ptxEFLHwSqkjfc02shcBSq6kx9TEUP9vSOBTZS2n4pXJ5tNBStyYaq6gjgV5vo/JZ5AT/JjTfJgE88Q/FjNDRoa7bk00IesBtDI9KGumyR1rZ9Jr7gGbLYl2XfYwb201mB1NAKykLgQF/BI2mwx2XC0KTxt/SnXo8EEN+ZIKzky0SYNVDqgCOckSRKJ2hHBNI5UgeXT8Kj/k8mGmZGfXfDrvrYkZbuLSjUpNFU8VZSV6IdtagtIb1KzZZICmjMvXoeUd+eOhIqMlehG66uL45ea8RCx1lEtTwvFQ41VqX9imYrpf43mYcm/kGI5oSNZPl7Kdef2V5uMBhgS6te1hFPTHiMsApM/OQAj7Z8EqQzJYhB+1onlwxuBpTEoyImiA+adjeQNrCsmJJKYkHx8Oi1CIGf33p64DnvP0inzNTF6Di/bzIdrFCSK8J9poeOagIQvEe3PWVpOsGqISAd9uTRZe3YqLFKaH5LCoiYGConu5aLncEz0YUclBokoIdfa0gLjuapJlDsF2O5ukHIg==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
