---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCCcQYphfikWo3xnrx0eH2lzPbpTHt13fM+UXbrD2Bmf3+aP3MKNU/lS6yrxjjhjJTf2xIFZE7BtNS+Ze1XQ1Pv9KbaUWd6wGbsHb7LJy6HOnI2rtWtIwnsh4B5X8vOLMoM4g9O9BF0ZEV76FYEAqgWPwGcLTD+KpaBG7gZc+GTaIPj8ateHosqFPGboLXh23t90c8Wr36/LNifepZqI5dxrrPnj4yUZfgH3+eRQ9DK0MWLSM2VBeqY8upTv4VLKyIQYByGV3r4A5lJqBOKumP+fGY1C7tIQxy967NAYmUeu61wjNOcBVYbBGnjJleXuVrRb4vHL+/Ruocn+hH1Wc311nu7dMtVOdoFr9zArlv+IiDny6mOyCU6hgUSeWA1ufr+E5ebt3gXtGZ6hxyGhsCtv99YW4Dzye8NQFbXJi6ayJJ2P/6AeiFMIeAnoIDIsW+s9H5AdGvk1VRlO2FV7ab0AG/3RkUY1ugV1AIQKzOJ+B72q3IZxmESIKcjT9MDnItUbJUUx2SEs2Osd5dHiRLDFQO0IJmFaRgEdgJtBcPMlvOD33i7wGWWYPHy5gcBrsmJgUutAc0c5/zgHiQ90lsoGhyZXcffKtj+jPwEU/oizG+Gs5P1VEuRlpRvlxTiNM68D9qHnqPUZtAPEfOt+IjDGdqDeu80XlcRgBbJP9pK1k/x9TJasZS5oY0kTln6YE7nSdEUV1T/HsQiH1VrDOAyCTX55+BK6u/N9VJ+SYWPkg==
    username: AgAYeh+IeRbBvkduVPVVdQsqCKRtHd3zO8cDksOZMaa3UW0hFvzPJLRJn4xMbBQU1gIOV0WCNG09EokMLdNjnwc6il+juMBwMnFpMSRAMjihYfloqw4WRC/R1zLmB+AAf0CmyjktbCoCogFEunHfpABIsokPE52+XQU/KsUmgmrv6Z7jDnDs7K5QP0xYJwUsP7kK4lbog/350wX9e3QiaVpBh9Vtq8KimjHHg+U7rtVWy7yC1sGst7oyAe7UiMCJp8rvvcW//WETU6d3joYEvCBSHkm311SICrppdTQkQCovT4H/DTPCBa0O+q5e0pykZDOn2JilmMfNImo7DjHlXGsyV3DSW4T82+F5uu3HSDo3fNrWPKK7TK4MQFpsgdUnMF90VxOS6SeTJddK8TvSlIzYta6h2C9JJAXmdqU9SDL0LsQt+K7ix0ni5Ua/Z5ckfpUNoDOGJ0qTjZthXLJYu+E7H0fGGNFPYnlWxEHqE0QqNlwZRgGtmsCg/nMQFeUytHwBnwk7S5jViVTDeUhCJH0Okr2GAWO0v4e2nb1dIPPEOTNQXoPvaIYgEmRyOu+0CSPMlbpY6JoXmsVgvM4WtFCOEahI5uKtjD1F3vzhiMjgUVRAojmT2d6sb+LX8VoAOZLCeff6pO+E0i+dBsFd31G7sdrH6x5QUmUO1hC6Hd+E8c/sNMHOMXMyVPnDDbrD/b2zW25ybA==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
