---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgCOugOjUOYgOR1ytyx4DqBlVVLsIHdiBwwH+WXRLUx8cgqFDSnSeOWk8fEp73uBsascuAWMo2zPnsUllQNAhZm11uxSYysCMgqDnkGWPHRkxWDbrUwJ8OfiZejAYupriiQRh7IkPaotpOTOQrJAyLMQcYGn1bmISwCTkiGJwMci0XwFTRj5KCYgPAdXLsHvQIQa/fZmLJS2nGxMWxcA6AkS5SuvoKH5iDNDvE2LlQ2zSG/uLY3QFq0WhmGssV2S/JgxiJ3vExadr/OpL/OqZaBF4/HK2LCX5WqUCvHD38YTn/wMTt3PkAqWtXb4AyEj57QMtAiwa4PtTf/FjkuqEvYxlgcupynB0GBHilD+S/q7sqnLUc13lwVPd7iZYDS1ot0l3pNHIG7bzLAH4YQk/dP/VJVq+BPoRkcsBb7c0CArWiqGJywGmR7NI4WkJYA5Zs+Cx2Usr7kGi1hRZJcJRfeQ97/bevcsbPq9YuRJgV/fgPi1neusM6bGxfuNyh6daELeatwrj2w5y15nLa417v/6WrGLymyVkmzHpNKvh7KThTNrpI7VfWyxjwK4/kovJMfKCjq6F6kMCnXpsynEFNyOYKa479LDPfyoFA+iuPrwVZjG2kKJ+DDkn8nO1EoHe9OfdkC6dtmZHzdEzqvFOk5UVu4oV1kis51IvDa0RSKckZQU1AKSnyZ/ci50AmZbwLZ07xVuK230uIvEu5dcEIGroRA0pYke4166S0XVtB7UtPxxwHYeABHEGSVF2hbK3L8j03K0UdNyCYQ4KWc=
    username: AgAamywigevaKTu2feG6fUbl98Kxab0Hg+yLNa8V0M3obN4RbBrmy0vJu0Wpwn1uSwhmM9724t9CHtyQUxBtuIm10ckX58wEj9Ye/Cc9zcc6CuNz5mAuiW+mLGmtYCwAP+viCea7S/XQKAlAlIyLce5NEUzzPEszH5Xe8fFv0BGPhvQN2NQWXZS/C/lo4yDhQ0VWmCP2SkvrXvVspnS6djlRPMjD+yZaErhY2h7BpETZXGYUK6Q7twFBQFjO2OUoXHVOBmLvCPU4FTKVrcjXKhizPAKsXQU5AbXoQ9Zd5g8TtRghpNFMk6UUFgfsR17RZm+LDqVAeKzsDWNLb4WCDrCBOKhBmC+YwwYlWJnR2dV4jaW+gkad8oMPrQARjf7xapDDZUqo9DoxzYfCYR6A4if/IJIPCIXj8QWcS4wdSjT6AaEceuM+gsbummDTWKyIcGNH+J1fTjqsnP4+7CxcaxdFlT0eHswWUgygQDm0NdXyVeCTdloHeciBh4e2d4EXKQ+QORvhkCImY7n6w0N+mWS2OWShfgdi1nooYhn5/2nFxi+vD7TIftr0ir9Pg51rzJmBMQjGbB3c+jSzNymH8+sIOhu55uerdOA0vJzSqHWA6qj6KprrAwQ3ReCVcVVB8LvbylMUExvmlSBpGQuT8kIEEFN6FLbmblNo00NLkSnO3z9StQkGtOfb6HLEd1DPsAFijuwwaw==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
    type: Opaque
