apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: weave
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/weaveworks/charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave
  namespace: flux-system # todo: change to sys-weave
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: weave
        namespace: flux-system
  interval: 10s
  values:
    rbac:
      impersonationResourceNames: ["admin"] # must be same as username below
    adminUser:
      create: true
      createSecret: false
      # todo: this works, but didn't work with the sealed secret. The secret got created but we get 401. Maybe the name is wrong? "cluster-user-auth" or the namespace of the secret?
{{/*      passwordHash: $2a$10$iz/HoXf9cApTVmaX361t3O05M2QI6.7rRMySfIjCINPqT61whJ52y*/}}
      username: admin
