apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  annotations:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd-parent # todo: consider moving this to a different root, like base-root that comes before platform-root, so that if someone wants to change platform-root, it doesn't delete flux' helm-controller and everything stops reconciling...
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./k8s/platform-charts/01_fluxcd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    chartVersion: "2.16.1" # https://artifacthub.io/packages/helm/fluxcd-community/flux2
    {{- else if eq .Values.env "stage" }}
    chartVersion: "2.16.1" # update also in bootstrap script
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
