apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd-parent
  namespace: sys-fluxcd
spec:
  interval: 1m
  dependsOn:
    - name: platform
      namespace: sys-fluxcd
  chart:
    spec:
      chart: ./k8s/platform-charts/01_fluxcd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: sys-fluxcd
  values:
    env: {{ .Values.env }}
    {{- if eq .Values.env "prod" }}
      versions:
        fluxcd: "2.14.1"
        cli: "v2.4.0"
        helm_controller: "v1.1.0"
        image_automation_controller: "v0.39.0"
        image_reflection_controller: "v0.33.0"
        kustomize_controller: "v1.4.0"
        notification_controller: "v1.4.0"
        source_controller: "v1.4.1"
    {{- else if eq .Values.env "stage" }}
      versions:
        fluxcd: "2.14.1"
        cli: "v2.4.0"
        helm_controller: "v1.1.0"
        image_automation_controller: "v0.39.0"
        image_reflection_controller: "v0.33.0"
        kustomize_controller: "v1.4.0"
        notification_controller: "v1.4.0"
        source_controller: "v1.4.1"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
