apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  annotations:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd-parent # todo: consider moving this to a different root, like base-root that comes before platform-root, so that if someone wants to change platform-root, it doesn't delete the helm-controller and everything stops reconciling...
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./k8s/platform-charts/01_fluxcd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    versions:
      fluxcd: "2.14.1"
      cli: "v2.4.0"
      helm_controller: "v1.1.0"
{{/*      image_automation_controller: "v0.39.0"*/}}
{{/*      image_reflection_controller: "v0.33.0"*/}}
{{/*      kustomize_controller: "v1.4.0"*/}}
{{/*      notification_controller: "v1.4.0"*/}}
      source_controller: "v1.4.1"
    {{- else if eq .Values.env "stage" }}
    versions:
      fluxcd: "2.14.1"
      cli: "v2.4.0"
      helm_controller: "v1.1.0"
{{/*      image_automation_controller: "v0.39.0"*/}}
{{/*      image_reflection_controller: "v0.33.0"*/}}
{{/*      kustomize_controller: "v1.4.0"*/}}
{{/*      notification_controller: "v1.4.0"*/}}
      source_controller: "v1.4.1"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
