{{/*
apiVersion: v1
kind: Namespace
metadata:
  name: sys-sealed-secrets
  labels:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-parent
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: platform
      namespace: flux-system
  chart:
    spec:
      chart: ./k8s/charts/platform/charts/01_fluxcd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: {{ .Values.env }}
    {{- if eq .Values.env "prod" }}
    versions:
      chart: "2.17.1"
      image: "0.28.0"
    {{- else if eq .Values.env "stage" }}
    versions:
      chart: "2.17.1"
      image: "0.28.0"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
*/}}
