apiVersion: v1
kind: Namespace
metadata:
  name: sys-sealed-secrets
  labels:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-parent
  namespace: sys-sealed-secrets
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  dependsOn:
    - name: platform
      namespace: flux-system
  chart:
    spec:
      chart: ./k8s/platform-charts/02_sealed-secrets
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: {{ .Values.env }}
    {{- if eq .Values.env "prod" }}
    versions:
      chart: "2.17.1"
      image: "0.28.0"
    {{- else if eq .Values.env "stage" }}
    versions:
      chart: "2.17.1"
      image: "0.28.0"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
