apiVersion: v1
kind: Namespace
metadata:
  name: sys-cert-manager
  annotations:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-parent
  namespace: sys-cert-manager
spec:
  interval: 10s
  maxHistory: 1
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./k8s/platform-charts/03_cert-manager
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    chartVersion: "v1.18.1" # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    {{- else if eq .Values.env "stage" }}
    chartVersion: "v1.18.1" # https://artifacthub.io/packages/helm/cert-manager/cert-manager
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
