apiVersion: v1
kind: Namespace
metadata:
  name: sys-weave
  annotations:
    linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-parent
  namespace: sys-weave
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./k8s/platform-charts/03_weave
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    version: "4.0.37" # https://github.com/weaveworks/weave-gitops/blob/v0.38.0/charts/gitops-server/Chart.yaml
    {{- else if eq .Values.env "stage" }}
    version: "4.0.37"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
