apiVersion: v1
kind: Namespace
metadata:
  name: sys-linkerd
# Do not add the linkerd annotation to linkerd's own namespace:
# labels:
#   linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-parent
  namespace: sys-linkerd
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  dependsOn:
    - name: platform
      namespace: flux-system
    - name: fluxcd-parent
      namespace: flux-system
    - name: cert-manager-parent
      namespace: sys-cert-manager
  chart:
    spec:
      chart: ./k8s/platform-charts/04_linkerd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: {{ .Values.env }}
    {{- if eq .Values.env "prod" }}
    version: "v1.17.1"
    {{- else if eq .Values.env "stage" }}
    version: "v1.17.1"
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
