apiVersion: v1
kind: Namespace
metadata:
  name: sys-linkerd
# Do not add the linkerd annotation to linkerd's own namespace:
# annotations:
#   linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-parent
  namespace: sys-linkerd
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  dependsOn:
    - name: fluxcd # not the parent, but the actual fluxcd helm release
      namespace: flux-system
    - name: cert-manager # not the parent, but the actual cert-manager helm release (issuer pods need to be up)
      namespace: sys-cert-manager
  chart:
    spec:
      chart: ./k8s/platform-charts/04_linkerd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    versions:
      crdChart: "2025.2.2"     # https://artifacthub.io/packages/helm/linkerd2/linkerd-crds
      linkerdChart: "2025.2.2" # https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
      linkerd: "edge-24.11.8"  # https://github.com/linkerd/linkerd2/tags (use edge-* release that corresponds to the latest version-* tag, and NOT the LATEST edge-* release)
    {{- else if eq .Values.env "stage" }}
      crdChart: "2025.2.2"     # https://artifacthub.io/packages/helm/linkerd2/linkerd-crds
      linkerdChart: "2025.2.2" # https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
      linkerd: "edge-24.11.8"  # https://github.com/linkerd/linkerd2/tags (use edge-* release that corresponds to the latest version-* tag, and NOT the LATEST edge-* release)
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
