apiVersion: v1
kind: Namespace
metadata:
  name: sys-linkerd
# Do not add the linkerd annotation to linkerd's own namespace:
# annotations:
#   linkerd.io/inject: "enabled"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-parent
  namespace: sys-linkerd
spec:
  interval: 10s
  maxHistory: 1
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  driftDetection:
    mode: enabled
  dependsOn:
    - name: cert-manager
      namespace: sys-cert-manager
  chart:
    spec:
      chart: ./k8s/platform-charts/04_linkerd
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    {{- if eq .Values.env "prod" }}
    versions:
      crdChart: "2025.6.4"          # helm repo add linkerd-edge https://helm.linkerd.io/edge && helm search repo linkerd
      controlPlaneChart: "2025.6.4" # helm repo add linkerd-edge https://helm.linkerd.io/edge && helm search repo linkerd
      linkerd: "edge-25.4.4"        # https://linkerd.io/releases/ (use edge-* release that corresponds to the latest version-* tag, and NOT the LATEST edge-* release available on github)
    {{- else if eq .Values.env "stage" }}
    versions:
      crdChart: "2025.6.4"          # helm repo add linkerd-edge https://helm.linkerd.io/edge && helm search repo linkerd
      controlPlaneChart: "2025.6.4" # helm repo add linkerd-edge https://helm.linkerd.io/edge && helm search repo linkerd
      linkerd: "edge-25.4.4"        # https://linkerd.io/releases/ (use edge-* release that corresponds to the latest version-* tag, and NOT the LATEST edge-* release available on github)
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
