apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-release
  namespace: sys-rook
spec:
  url: https://charts.rook.io/release
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: sys-rook
spec:
  interval: 10m
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: rook-ceph
      version: {{ .Values.rookCephChartVersion }}
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: sys-rook
  values:
    logLevel: 4 # 0-5, where 5 is trace level logging
    monitoring:
      enabled: false # todo: set to true once we have prometheys or mimir
    csi:
      serviceMonitor:
        enabled: false # todo: set to true once we have prometheys or mimir

      # controller/provisioner replicas
      provisionerReplicas: 2
      attacher:
        replicas: 2
      plugin:
        replicas: 2
