apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-release
  namespace: sys-rook
spec:
  url: https://charts.rook.io/release
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: sys-rook
spec:
  interval: 10m
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: rook-ceph
      version: {{ .Values.rookCephChartVersion }}
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: sys-rook
  values:
    logLevel: 4 # 0-5, where 5 is trace level logging
    operatorNamespace: sys-rook
    operator:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
      allowUnsupported: true
    monitoring:
      enabled: false # todo: set to true once we have prometheys or mimir
    csi:
      serviceMonitor:
        enabled: false # todo: set to true once we have prometheys or mimir
    cluster:
      spec:
        dataDirHostPath: /var/lib/rook
        mon:
          count: 3
          allowMultiplePerNode: false
        dashboard:
          enabled: true
        storage:
          useAllNodes: true
          useAllDevices: false
          directories:
            - path: /var/lib/rook/osd
