apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: sys-rook
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
  dataDirHostPath: /var/lib/rook
  mon:
    count: 2
  mgr:
    count: 2
  storage:
    useAllNodes: false
    storageClassDeviceSets:
      - name: set1
        count: 1
        portable: true
        tuneFastDeviceClass: false
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              volumeMode: Block
              resources:
                requests:
                  storage: 10Gi
