apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: sys-rook
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.4
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  mgr:
    count: 1
  storage:
    useAllNodes: true
    useAllDevices: false
    directories:
      - path: /var/lib/rook/osd
