apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: root
  namespace: flux-system
spec:
  interval: 10s
  revisionHistoryLimit: 1
  chart:
    spec:
      chart: ./k8s/root
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: prod
