apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-cluster
  namespace: sys-fluxcd
spec:
  interval: 1m
  url: "https://github.com/yama6a/k8s-full-native.git"
  ref:
    branch: fluxcd
  secretRef:
    name: github-api-key
