apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 10m
  path: "/flux-apps/platform/01_fluxcd/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-cluster
