apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: sys-nginx
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: sys-nginx
spec:
  releaseName: nginx
  interval: 10s
  timeout: 2m0s # todo: remove (i.e. back to default 5m0s) after testing
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ingress-nginx
      version: {{ .Values.chartVersion }}
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: sys-nginx
  values:
    controller:
      kind: DaemonSet
      enableTopologyAwareRouting: true
      podAnnotations:
        linkerd.io/inject: "enabled" # linkerd should intercept traffic FROM nginx pods to other pods in the cluster, so we enable linkerd on nginx pods.
        config.linkerd.io/skip-inbound-ports: "80,443" # linkerd should NOT intercept INCOMING traffic to nginx pods on these ports - there's no mTLS to terminate.
      service:
        type: NodePort
        external:
          enabled: true
        nodePorts:
          http: 30080
          https: 30443
{{/*    namespaceOverride: "sys-nginx"*/}}
{{/*    revisionHistoryLimit: 1*/}}

{{/*    controller:*/}}
{{/*      replicaCount: 1*/}}
{{/*      # minAvailable: 1*/}}
{{/*      # maxUnavailable: 1*/}}

{{/*        #config.linkerd.io/skip-incoming-ports: 80,443 # todo: check if nginx can see the correct external IPs. uncomment/google it if not.*/}}
{{/*        #todo:  add this to all ingress resources: nginx.ingress.kubernetes.io/service-upstream: "true" (makes nginx use the service's IP instead of the pod's IP - and thus allow linkerd to do the linkerd magic)*/}}

{{/*      extraArgs: { }*/}}
{{/*      ## extraArgs:*/}}
{{/*      ##   default-ssl-certificate: "<namespace>/<secret_name>"*/}}
