apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sys-sealed-secrets
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: sys-sealed-secrets
spec:
  interval: 10s
  maxHistory: 1
  releaseName: sealed-secrets-controller
  chart:
    spec:
      chart: sealed-secrets
      version: {{ .Values.versions.chart }}
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sys-sealed-secrets
  values:
    namespace: "sys-sealed-secrets"

    image: # https://hub.docker.com/r/bitnami/sealed-secrets-controller/tags
      registry: docker.io
      repository: bitnami/sealed-secrets-controller
      tag: {{ .Values.versions.image }}

    logInfoStdout: true # whether to log info-logs to stdout
    logLevel: "INFO" # (INFO,ERROR)
    logFormat: "json" # (text,json)

    resources:
      limits: { }
      requests: { }

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          # Anti-affinity based on Region
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vault-operator
              topologyKey: topology.kubernetes.io/region
          # Anti-affinity based on Zone
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vault-operator
              topologyKey: topology.kubernetes.io/zone
          # Anti-affinity based on Node
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: vault-operator
              topologyKey: kubernetes.io/hostname
