apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sys-sealed-secrets
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 1h
