apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sys-sealed-secrets
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sys-sealed-secrets
spec:
  interval: 10s
  maxHistory: 1
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: sealed-secrets
      version: {{ .Values.chartVersion }}
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sys-sealed-secrets
  values:
    namespace: "sys-sealed-secrets"
    logInfoStdout: true # whether to log info-logs to stdout
    logLevel: "INFO" # (INFO,ERROR)
    logFormat: "json" # (text,json)
