---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgCY2xAIcn9ekYCw75VaaK6JCyuocJQZ1LsyA+U9vWeMsKiA1eAaHzdMQd5wW/DjYt6iSY66I0YhxPKaMMX9upjyPJ/zANpz4ndzAQQrDMGaYIZ4hk0AAlFzwSs10nyTHia7Km3DlijTvbuTk68fasu5ph412oviTyhbzfY7RIty9ncGYAPEQi3GVFcvxmCAvKMi2OtCYih6AoV65JisTiPXLOBfAZn9SIsliK7Ius4PXT/Zoi5TMDw6ypoJLke4DHL4pDdMeujyRTRNIOLzyg8OG/p/4MXpQwwtIHeDyJoquWzJnbXdq+7bjKf0eX74ki1o0EcJMtnm3mggg3u2JtZ0npud4E89wAGJKtqG2Ch/og9tKSSFQPJx9hwIWe5ZBjVaunFRovtTR/9yzZU/HEICaqQWmD9/pMcFDu0kxUBo6lldPwf7tAvR0j+snR9pCT/gKZJ5K2wRgDcf7KNrOTkrPyaXAU+aH5Q51pTKWnP/zUNnHmr4TgY8TcZgJvZ58SLEVvpo3B89R46UmrFUxFCKnyXBsyv5QSqSYVF2jn3wdqdiIBkliMB8uXU2r8JN68/btEBZZ0VJgwirExkZdkbSdIqP4JJZk0MUDv3asfAbWZKlae9BqzkJZA10fTxHoQRcyljKzYas6c33m7m5mXYVv+hD2ACeDJdS1THCotfEpaRlFmNQSW4QDmkYmpvJY01YTwIl5woJXkQYoWeTWAe+1SXBqSk7rNO+b49s7B2GS9mbZ+CsRLWSy8/hXeAIQ7KWDoqvXErGgAoZBPib2Il4feG3OPuGPA02RWV6gI9PlBT/k2HUaLlc5aslPHU=
    username: AgCHFvTfnVR4enqJNCZMCSyWbpkwlII9xPPoOdIhrB35loeqw1YBNhHpdEAiOaz1fJPKq/Pg4K5XL+hsi0D339qI1MIAy+56L5JYipi7fK+Pzmac/0Q3pg/KFvb6hVQQPF64NTyfJVzCxT313cvtf8FzVW6LTcsF3DXlPoRmrNN0bI7gEG7u2kTpUwtsiENmPz01LOX0pQg6q/B2vBInpwQ6nxdoBylxdKCAnl4IYdFAq/0JYzqtXfEM06gv85fZMlXbUQOqAyt/+6BHVWuqckR/DWMrlextwFhljuuz93RSj5PamcR31hZowX6EKgvfHQSj8VxHTVAkI5bGIwtiaTm80tMiR8rVJBNwuezQkGY3lOS7hODzZ44xdh9k1wJX5NwrydSpEhk2KAP0RIYqkQWUSy6UqVxrlewoXl64WImmVWRqn8+ADwS9LJAVSWB/aVaG01nvKD94XDu0jaSMkBvI4wRY/tjECrjd0OEdDhAmhhLuwP81mIEfcRmZQRTHpcgAaA7cJHODq+8lBDg61ATLguUACpwLzWomE1lnK+Ne1bJBwhOsamAaZTGnatJ3aTCnXhHS85ST+YVWP2gY6TdY4xbtSBjWtJvpWK0SR8K7saJ5rmTtvKuT6yX6hRTsHHTSLAkj6VM8sUTfLZ3EShvBGsdXFQytBwkwdwc4OXUdMVAJTGpkh9gVCY+QuN5qtecuqWCtyQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
