---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBPYv0zAtDR5DSYbfFh+Heorg9Ro8Teo2AQtBb7nSOt6hUK0xP+9TfjH6mv6WVU2ztcnN5WznRunP89VTYtSrNqow+vGfhgkrQtoYTtdKTNG7YZhk5QY5z4GytDPqQMuwRFZklqceUXK8e1TUPsAm8SYUpLQY5MKfKGgcSzCxvYsTyzLY6A1O25dkcpuYPWeYIfAPlZLI3A7mx0Cff47XOtpGR9Xmh+sneAy7/uyFC5UqncJPO8uRMEa6SwfioI7qaPmcnCr3kPGJ/1digTv4YEQmx3jJ62JmBXWc3OsJ0/d/LpBHri2rLkPbF+w9H+VBL3OfrijMO6R2Ek+cOKXklQBJRH00b8EJiCJ+LacOfDyu2CjkuxtyZIRXFEp2XQugm5q1LgWqHpe7E2B6OdDzCBo6SjgpMqgtV3MSp+nDp765jzV6H2PWdu+5cPlamUfQJb2HnTZdM1ZUvxCNWQnQLQq9NUrhOAxs9UMycMUoT6FM538Z2hDrd4rHnLgIl98zY+nCUcjQiYTkI+Gl5Vid/Hfx/Ml6OO1F1UKukYmMb8/qaul5xXsR9/lPnN2fq7+9affgv/69UKjri4kyA2pKCCI/cfZqDqtJP7M7T2F9yWm/6Shfr/1ajnukubm9lQeM63rqrpHd/soEQtjRq0y3k58478M700VHIZnkhDfs1yZC7X9aPYKNAoa/GUTZOTE8ZZKviaaaY8x4Lt6ng9OJ3Hlsw8GGQhDFX3ZKLO0CZixhxs+O/Q0nnH8l9m0XQVEfmzwAalvPgA3wRU1tBu0ukRnzkM/H7S8JzDg2hxnU9UwiP793aYEwtEvsTqb2s=
    username: AgChhaF23zBUX7D330fwI+8ra4glXyvpSSR6eX+MsbuetVRGf20xJniEI10QGSwUokeySXfluFN3jqv8HE9+xXkLSy4YdGK20rJdl+emfYsIMwLOUgP3W233DR+8eK4nX4SSX2pEM5rC3YeEyrdAKrwCgIIEwZkYVKNVqWo5eaTdlkUWtw7GstScyqkyBkmoN+IQiO0q8BCzu6NDVhPEF7QrmK7SeGl6+99lUbNdm5sLUATaCX8uhodH5mG4UKdhc0DmCzxZdY8NqMfq/AJfPcVdFgsTYY+UAKpmu0YytMejheTe28GGaGF5m8GCojbFqcdIgRiIgFIHZS7RNdzcukfjvpqZo1iSqSMx6jGzPcaEypYVl6STK/BK58uViWQNmRlufByb8XkkF5aiQQbvYuDxQhC+qGu5gUFKGXYcUqJvFsCO0WYR0mFr+SREhr1qr9OOHkQCufRkIgyvy0mbpDpEtA6q1HBlt+81sU5GQMbRgFHzXk8akKyVr0ZSUJdttTE8RMIg13+yx6mvbEkS4xU3ECf1i5mEKmStM6UndLZmBBMAQlpdHsb9rGwyUaJK0q4c+MHvNFwlZ1v4I/TpXquFxM08qQphs/JaN8kasiz3ygc7DU+YDfCEUPlaGlF16icClJIGugwoyuYmBWq2JIgJWeApvI6vsDAtYvDC0bEzffBn2rP6NSVP/WU7yWkSIR4kGbfudw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
