---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAsH2nvo4ZnPGlaWnn6LDG2OZ7rIknZ9ONc6qa0d++z3lmAMfnJDkenBsEyKzcYdHNVQJzoSeqQKuYqWsepuWZS2oB+oNIX0/u1sP49OpXA5IiZ5LWbUtPGjVDuNKccBlhCVLudr6Eo53dGEfuLbflG+o5iGK8/1C/HasGCw1i0NflVLF0r7/sLtQUwaJ6/QobCFL3BXGdnl0OXiubdpTr2kMvChPmh8VtOA0OmA0UNFvvlE9WV8AtsBOkVX9O8XlaFwuSBY0iJRkjf03sUL6KHwNehcmJC4Xucxg+K6yihauaDriDMHlh7xVUIBJVtF2JToKEZJPLB4Y9jhpa3gVAy1exasZ0gbyeJkaU54Kn7O67JQO/oEvioHVhgD/MW5oNmAW27Ub7/I9ub6X6FmTLlRcPokNPZF86W/qlbNrlDcK5g6OrdtzlEAD5YauPXFrlGVIs+F9N4FCJLye+ejgacv8nvc8l5nwZ0M/HCVW8ltzxx0imCAt/r9rgpp3HeHGQvg6Obi+s7EaHSsE5j0JfKcNjZh6RieSsthITbA3/2MMMcIVr0A919cPgi8g9jwfXI4zaFWX7omjeRFqukz03OIeK+gl3laZ8GkV40R51fuLsJ0A4MPpq9qUggERt5Du14ctNpOCUGlz4y59NX3CqKf5ZQYbvicH6S2vtNu8zRGnto7FBGmoB2Rp9OvZz75HMtOyYa0oXHkrQkk9/oiIyWe8Ol1RyeTRWeVcKOaG52PlPa5ibss+IzNo+ziv0gSWz6hC8jo9XroED24jrFiOfDm2m57I7tB3+/1J7Pm/KndAhKrZQ7DpF0l7hFfk4=
    username: AgB2quL0fy+8uRO6dCGroq3BxZ2v5yFJgJu5+Ech1RIeV38wvMRZjg3VD3RB8Lm8VEPZDdZtglHkQ4PuKOf8MDoQf1aBZ4YbMmBdd5FScXcJTAjdrNXbXpOU2YvoNJe2TFoLFIom4xOAlf1p7sCZm+4n1wHLZQeMbxiBuPiwIk4bbpbU2CXSC4gD17d0n5qs1SgvFRHdXvg5S7vcwhTovP7oBjoS3snvYanbeg16C59bgv/3R90OkiUEZlS1cjTnsyWaPKV3HUoFNAbGTISeQTbZNBpBgB2xi33wmwQof5UduVo4E/5CSsPpq692+7f37uuXzXWBgknsRErTZISYsAYEJLhi8n7aGuhiwdX+VQg+RMaFbDFV/mAMtGe5ZxDEvWXy+whZsg20S9u3FWKvyAJC8d2+fk4u1giRlf6aBjV6dyD38PTiZDfpjcVfflz42N/MPCc8I8JE89C0SqUSebGjA5uiTdwpxGFXFxhuA12ybLV2MO/zMqMsmHg7aNICu0y5FFRUDlMiEAUy8NlxJr6y5xWyPLb1ld61ggT2HOfV8AjAJkofToC9sZXTLLnim8qXB3YiOBa/5H6DtA4Tt+RKX95/2umHkC5J2wY+bcK17hQXAEYA1UgWmoHAZz1/cQkXbAhS2viVSo3IJWVeIWk3otB/a4NznVTPg5vkadYz8FKe1LYXCfozrrEpsAF47BR57Yrl2Q==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
