---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBjVQ5Wb4Mp6izVgq2rtP3l6NxlYNMeoDrkiM8zXvnkUSjsHjjYOBfPpgfa7tQLrgztUq9Ui7/YrU+0yMvO5xvb3vVMFxStP7diUVnIU5uQJx8WKXmd+RgMPwrOxkQleG9EU/GkRS62g/UPNyNjYQ0Fo5ESXvHdSaeGxl12AhEJcStIMMjCOdNx0KKYhTRAmsX12uRlxeFRZHECwM80WqXYYerI71tG2UW/MaLKsDQaCVa5BIHbIfrwJk/TSvaTTArfJ+hXTLIGoqUEW8bJhtGnwf+UMuvyoIYFUtKLuLhEzm+LAYowU5t2GYPyMGwDoDYv+IPrXN5T3w+NAoTefoSgP+T8uYX63z5OCB1SkiLHsVwAmZBt1/kx7RWvGGIDFo6oTnvUp4baq6pYSLQFnMlR+EqaOj+b+6BKtAAe49S5mpO+IBK0DAA0cD6iZqIPcjw7p4X/d7dtcvRszz9pyLH5fugObwPRXWFmkxKpI7as0ggv7iEt0fzpTmhKqDS6ZK3QIcyNXYOTMHvZW3RDRirmoKYHVevsiQGj821SCjxTjhE6YwwmLioIEg/Ow0kmR3EDsJQos8OPrJSAvibJM3vP0XOXfZ46+gwH04ayBrVQZfp4rU66cgf7WOW7kPlUc+/S1xHB4cT8GEvYfaLoJ5NKcZB7SYHfFhd+F51hH1NKKLxq5isvKqC9t/aBsvLZyLlzkV4ucHrwemsaVoFO3z2908UDAxY6Y3SLWOKf12Va/nD1j/oMOMVPpcQ1BxMW+Oidj0WqnOaM8wXZ60q5SsnRTU6ev71I1qMyXXq7RaFL2MQlNiUiXNpS0VM4i00=
    username: AgBH2s0fjNMgloKm4QUsRawsvmA/jXDVq5QwuFZ9khbRFpjJlZk/YC6JemN+EQdCGB3XlfcdS4TL0OLnDTIYQQqo/y7PXh0gTWN7yNoixnuGtvuK0IaPl40Tekgcn2Fp+zSAJd9p3d5BV+0tsBzVlXCrauUTys+V8QKi6zShNKf+YluwsnFO0HlLIFwVQH01HaXeQXP4gfbIwZO67WLOvmDTXFAlz9L36L/vn23dMPzFLPbyrcWLHw20TLJG4u16YfcuFhsiYyaQs5gh4YuhEPc+G/rXlfSDaIOBAbZ86BLLRJH586xrbHZbrG8QW+gXDT7u1rsupJNeGJEIjNtZ+QAF/A3kQKBG0FWLPhTcJpm6zll8pEF5fljFFvGODmt8OBSkx2IjfDpWs0uc7DDPzF5minGYVpyVcnebCSvcz7bvNL9w20YYpGpsfzec+wEXdlGNMi6F45DtxoNkGEEtZlDj4UdNFHiSkKuGg640ulZ1kkguQB65hk+f6RRC3WW/SI/GB1h1BoK8PV8dwrTkLuB+bCPRJuu0ijeq3+xrwjEBxzB0F1NxecEBRTV0bpwd1aUZimskJqwtW3p3vOemyb5xqX5DCcd5dM6yU+TaLgIAmC+wGQAbNV5oqQPnTizl/c30SbI1OmUm3MT9Yx6x6YLSQlZlvQURlJAelOTSX/FwnUrRvht9Q2+USnRk1r/RJETOPWAPTw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
