---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgA4mgvU1STpDu/EuE0VVMyXzdQ75QBJOQmMt3yjJOhjHqeIAokARWjlLSE3GrsNaUXIoLZl5uBhLsbZ27+a9kiRaxlHT2DjibjoYCMyvJdce5u1Q0hPlTpMFBKpNUC3wfpSU5wNay1ALIhzHMcjvLLt/JLK/ofVC880nuNKNCWiAlefHDysaRjOVJ5S4LuU3AKC+1anFyvavOSsSXMNfInY1NY5/NE9I80K4alVzTacPk9w28Cpiu19vVv0zGPadl4G0fvY3/47N1+YdlSNQC7+WLgM6t3fVRCpwG5Reit0POKHH0+g3hbogptzpyoryek+9O6FCXmRzqrZprNAKd1NvhWXYVG5jm1tuzVg3onyCT1GmtBvh5F02lpdJyVvvp/XrF5YRG1XVb5n5VHpxmEZgr6Vt00U1SkybFeuIEa8oX2KdM4fzqizNb/LvPna9vyndyTL33/XcyBFaOv61nNLyuOQp/3NBjqTDWMa0J9AoXsLUYqRqoxS/2vvuGC5tEkNmZ1sGJQwqicPtq+ml6m3pkd5HPV7qKNDEYfS7QRS6Wq2HfeKeYdRqPTEtJgvRt1brcw3rvwtviwOw3B0WPYaIQa6zN6M/d9XXTazcAH2hMJM1mHEQ/x32kYhaS/Z9rMi/M63/wX7NbFxPvoPKJaAxRDTsfP4nWDq17mVoh44SUsM1ptSCoGLNopEAZ1VJE+M+RdMGsAsDKNR/0otjfPOZNR2V0mMMRVpjoDZWq8BpRq8aGPciJ++rGU2ORSP3EbX2atAyXuakF5BH4faXci+ht/iHyvoPQALQJEH/M23StH/AsYsS0Vkiyny6vg=
    username: AgAf84nAxGuSIf7VjhR4V9eEyYmKgbhtbWyn02K4VsMIY5hmN+Y6Wmxe+8bx8u0G5xRZZ9ygnaHGlimqWjTUeEdoKp8qnawVyQfVo8kKwXBT/5aIT7jZ4DznjIg7EZw/W5Dhkyp4CedzidY6YlUAO5WhtgQDcMfZtV/JsYrLJtQNS2AnBLg5rTKsmLaRGRj2qc4eQE/EopudI8j0eF2ctY4tGV3Pgo6ZDhdojYXhPPTWM24jNjorLIFlQvDayEjbR78fI4Ag0kJcdPSAX+493Fbv3427aAn4RJEjD9AyffUGShebebSZMfodH1JNeKnxYFjnFGNi3aU7mp6a7PXYp2JRHbapP8OUq+OhflOGiDYNRphZ2qhNJhvglMd0r4wevOjfZ2PM51Bxrhbo9ruuSl52CQ9112v6Yt8gYA3xRN/Q0RsVfNvk8rx88PdrXRG86eTwrJR+ca7rFU34RLTFGN/PVucsBqQjeVC7CwzpgCMOmvhppQotRGUaQB5Wb/TRhxWC3TmfpDpPrHo4ueMycRWrDPdBMIhqN3duV/3f93bPWGai8p+qcUO7AwobY4ANfz2FnudPcgt/rKx25vS+4u2CXuTciXl/6BgaU6bDVXpZ9Ok8wCmYkiHxqylmzAenA2QTOkyI/oo7UloG+X74m59nzLVnATjWXbRSMTqw2K1rpcqcg/BNoEpbe1wYgor+JV406v+mKg==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
