---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgDTMadEm/6DtTwkaza1ctbXD3cPVhn/nL5F3KzLrhcDX5327BN1zpBgetARN6Sk1HgcJ02OJy3AYKgI0Byem8hI/5ntRGInyF/GhS2HDag8mJH6coPUPueKAMwunX7wJ1ORJp01Tb2GLiWKmslQT4YxBEkkcNgTKBDxHsRYyu3n95VlD3s+duRf8AkXur0j2BsPDAwue+hN+dqz2APnfwh+3KUNKGsw3dlO+a4oYbpwjZjEbWlgO7mebmrNiQot0cCU77YxAEGOOWQ7NEmO363E6ElGnkRU06BcrTho/MW9fKF4DzJjmlHuVXOhGTkVoeR63lMA7ld/Y0E9rkXt/nTGAnzc68cV149bLdhdqUfCdiOwDl/g8jeB5vf10uSW1XNOt70nGHQXcFotFHUsl2dN32K2G8gMfCBlLcesG26GqAOSIpXcabAnp3V45EGp2E18HpcdvHROKnJ8oS2hVsMnIIGP34ZxZLHgUZECx1nkU0PyiAiuQUPrlUd8XvmpfNJ+8bPS7mWqXVzNuRBPkO1uPDYSXrszl1cSCdeyZRyS8LrNLXIsDEd4o5hQRLnh/s+VCTpmgumauoBShqrXWKyMog+SJriD0wGpmUZlttisDGSxsd4iBtCoUBR25C72qsUPK+2p2sQSlh8ihWoBb+YjXM7RDqaYunSGhPFtLlYTIiQ1392TGjGtu6aVhvZe4GkPaqLEnh0/wQoeZRBeDudAa0IrnLxhmAaq5pOTaOAw77gxApTOQNUqTw3ENiw9pqHNnstR3VuThL/J9QRVrUlSIjClMhsXpQ+Sw9S4mDOXGCpQLir1Y25qofQ7DoY=
    username: AgBbRHYhKU0SLthQ5MgO4lkz8MocQZJ3YTJC+qq2ZIaORs10ejeK7RtPA7MjOEKkCpmuTxkqvyqWfTWbpXMdx7D8ZHwXpEO3Km/Vk2jvCjMTj5Qsbu2qR2S6qFkIRQ/9JvRB7RaPFQwBw9+18gtlcuKOwaMVXJ+uCzIdTHNhrmxTz90cFlg+buNBWDkzZj9RlMKcapoH5i8v5tWzt0nJ1NZbBjz9zYFr6Q3CMGRn4tynh7/kruutKuMEX1youz1Qs+Vy2umgVhtTRzwQBQ5iyyjnDcVXXuNTPSX3EOc5aIrPC1AXtEDWIBwfDUkhyCsA2Lz3+PoRX9kaFu46HkGCY3b/qGNeB2qLz0MDAwtNRKY4FeoFqKOK3U+cA+uq5A/gUzxGyyNArQhw+Gz5miPbJpslr8CBzWdsNfEOVls7vK7jEOvC5abGQwRnH0KxUdSJlykXxPXverC3edwkwPHxgxc+no4hlu58CKFNLO24aDn0EmfQKK6f0Cx5abSPOJ6A4tx01N7AzfM1iXxCbpKWDog4YAe8OEpcE6fxFWarLZVRynXF64fLNytyWh/YJQ2062N5ywsUbnJk/o91r2b8fy+LP+ngnaFTQ3Ko64unj284xEcC0hJ3msQz1pd+F713iVODX2vvn3JNkqp+3FpmF4fEk1unPdNna8uyam9lX8KeDhpnzAvQ0m8z/RJn/xLR5G31G77d/g==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
