---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBa7xHCZG5wbIg5FhJnIL4o2AGyZC0s0UpfITdQTE46Vam4PYKStwJNa12Jf7sUYnN/sP3Np2wI562quq36TUgOZfPiXvKVPazREenfTrPsQrF/YY3H+ZLjbLjajk705zf4aTkewBKUNPBcMfNh3B+PRjaNpYfZFyjX01xjqg1ApLaWD6Wmg85VWtigLlWS7f/j3fXLEuJCntVqYzMGvzUAChdAYMX/W5ef7QZFdRdOc1uNw1mUB/ChGFKYTaytEvIOMf+4G25Zh07jjbv2Kd9DevyaUWgZ8Vdr7+Q3VGzJ6FeYsHBm5xp0m1Z7TsXHEplPeySOorPKVdwjxvPYOV1qEo6i2cpc7MKCxW8P+1lEJblYDpGhgAh47zMYMj2j7OgNLWDJVgJ32uKy7jnjzQYKAsHP1GvVs1AQO6eZo9jn/1MkpU9qF0dxZMDYas4TX391XBFHLXS6eod0jF9OhWASEdEvEq00P6wFrswyKsVSVBsd/tUIHgGjeytFsi5f2PIKeDnskk5OgGEbRJKseK3yrr7Zlz9mTNOnmw+evr/FcrWQsg0qa6dVbKFz7I/jcK+ZcLnMZCPT6mI3ErhktgOvh1nlToDcHyU4O/4DJA83+l6JcM89tmRjWVMIHa5PoW6i6iLokA/iMJFjcMmVmBMLjQu3+qOM88MRoesMPgP8FIKrl8yoVBb6pc1sWQvugoq2igYkKO2tfMNRtuMLCiEjrEoWx/hEJfR9oAvyQFjCI0geGE5DEQLoSr03ggAs2Bf1NJGxgJFf7hKSiP76bD5f3wHz4EkKXQlyhBCKJ9nxYRXc5+yxichs0SinOlc=
    username: AgAJEmzI941kGvfhOtIIRfoZFY0xPdnVIwkhDFevpIQnaFOwpDUQBxyayk5vL07ldKizhKLrhyNjzt9wEswtOR8XUUya6KSUspPGWsRLDUCscYzkpTpZk3R8CvRvAj4mCi1bjJkiJynQOWTFYpc/zEiqmvY11Y6j+k3M7aXhwgr5ombuN2nPs7egr5tO+w9+YuhJb4KdEau31XgOacAI62e9d6CnIv/Q8boXyTmRj3IwiQvp+7FdOk+HkwdE6vtdjBq/z+fhI0nzkPvElDhUh/j+JZE9t/9aA1hqa+5EucuVF4qdvMHOS1FopliZpWKcGor9XUn3IYcLXW6PoC82TOmhLTR11Gs+Tw92MkVcutMHL8jboW0grh+qafjLijxVmj8Zbyr+cpeRqfeb+G04V7O6v1KCTwsleB0D/M28+xcCE28MpptYiA56ulguDdsYcYKReDR1dQVOzhwdoCF6R1EQi8q+sG+DeBa20FCvy448VxqLwlQl+jjI9ShJllXVjTjX6R6PYMIa4ySIk5yD66XFOTjk+50iiMoIp2VWIQ17WRFkKjCXJOHv9QnqRW50dUEr6rCYAfE2g2y4UfDHDFRmB/O+b8btTCtg+344J/CoKC90SUqMRlhTXzs5M/32MIYyZ+X7aN5F9HZfETMcTuaDcE773zVZHA8KoDqWQhZhag+mVoCjyyL86x5OyJEYye67DF0Mfg==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
