---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAguM2kgI0VyBHU6xVGmJunzP2n3e2drMqP7+H9aamrmAJ11qwXittCxY6AfGlbwKPUHeDwjyz9J+qEW+9Ut0zzOzsNiGO/FKcuBZPCiZnOUkNxynhG6820MOGUh5HQf2uLne4u4y9h4426TYwCxvejsilHvsr1XyNJ3/vW4/q5Ss+dyzQIVtxmZytBTSXD0ktWylCEWNsTX2IFuSLJcPL98g1RbJPTe7fSFnsFtbP+gsXjwba9ALPNhdyLDhRW69MWU9sp/Df7LZjIARM375S9J6DwuwF/ByLacqlNhpThEgjUWd0cZ4RzhbLAKjZrrc1GgQmaIeVUG4ilz1ECTWsLf4O3HkZRLy3LNxkVeZ+kV6/Rjca/v63SWDhnhm5yn+4+LHcjhwl/m3CmQqFxohFsrHi+kQs3M3ioxGici7vWa5OUtYPkDRfLBd/C7SHFjwPBSNDPt7uEAudcX7TJmgFdotEWoNSiz/4JxQDVYZQYV7J4rW4UmdgCGjYU54qNLst/mWYG8HhYYXIKueogzuYZUHZHu+wsXHYYjI0tKaCFJXpljqV7fUHiP287UShFrDCgJ+qhvJ0YilqasvUCzsEia96I9NsMF7B1qrOmEqWKbRAvvLAqXCKDm4M0GpDOfq97o/wK8eEGKoKfGSfXD9L2C7Tkla/Uk7yMdYMtghyapI1xFwZv/UwS4f+I+Tct1hxzyHmtcpIbxupiq8J7+6KPi5xWy157E0z3AY8JUZ/qLZucYA1dn3LUsf4KHUPIC5SxH8HKL63elISeRInf2Gbe0snnBMJYDv1NbaNMAXCmR5qj88FaEV85olLOWqM=
    username: AgAeN0FiYI4kC/QEBzmvMK4iZeatLN8lheEaoYhytso8vmzYY0RXbub2ORkBhRwskoUgEW4ALEl+1Ax75wYcuKQHp41YkXP1NuCiwbNYq7lnIeP2n74qzCupa9klnUsX8DW+QV5NttiUzV1wJTmHH4I62jojKVtYMA8X2b+1vjl38Ji5mUBzKgN0+skGQ9txDDfevhxR1Ethmu2OcAhDPs37mKf86b5BdV145x8wRSLBc4C8sp73iy3+jAPdbO6S0yPXwJ3Suo5RC7jHQlRXv/p80L3riJKegVdYXPP+TqQGxa8pKQ/ZE75sjRj9aXB1AeBklkWjETUWCKhG0FYAMBt6mUqfryd+9PKufLSa4Ir3GZVP3zbBcmpEYvqPGrZbscAg9o8rUvuFQ4toKHleoLJW3mT3YeIys1kuDG/NIJc9Y0c30ICP3k3eZb68P56XO26Wnz2a+rXRESTc/J0KAzY9jiOcgfDcVJUK48R7QujJRypu58r8eFJ5hjB6e6WbIDJskyueoaVxy9aKq0R1fbuXVe9e7w1XIfxw2VwdEpd1Qe66L4jzMgxoqDQO9OtLxB8X3ythdv9OS1wrCtqGUxFxm+snLKOwhoSAaDEILOFNWlhHRclPIgbZbkovFmaI37Kjedh8v83MksWiXuUTy4QD08ZAbf+wLwlatephTurkOuVu8W1wANjWdWelj1HLM/AIQW91Og==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
