---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgDNB5EQUGRSpSc/HxLAC6L7MOgx8AMkEUSu8tId+Jfupuy6964dRcLah2UzZYtOqYNO2zF/fRNw7AB5LGG2vdlP7Tzv2qqBsRYdTEQrd/DBtBiUZsp/pSZWt09KQmz+UFq/0QpoiG7rlrxQ5xGjskVakWW3kTZolv6JcrQLw7PNtB7BujHWJw6zCb7Je6Za8DlAwiWf+n5IOWQCkwWTuVNqMaATPopVsEjBRfybIwZ4nJIxxQCtvld3xOU2imb7N2IwgQ3ZJai7WpjgvkiDLmhMKyoEGX3PzvXoQgxhk+/rmNNJk//abf669Nwwwil4U/JhzIcdKav6rUtaFULCsV2EQLpbeEFcjdxXRXQYco0WUl7ghyVhKuBE6xdL/IqnECceWcYNnur7P519brVFq+OSHLlYbqkNA93zzy/40JTgpBhq85EO2/eJ3PzMtpl41QuIxnqu1vm+dOszR8xbslTV0/fb5ZLf9w02bqJPG3KESSgGvIYxvH3zx3Rde2bcYziKa6qG8CYyS9zXx0Glu93nOTpGqdoF1i7FpSMVaBUhqkYJaSPGtCx1iglQ2KmHAhiJh1iBT9MQKyEBQW11QWevGSnXoFtrF9xlB6i2G4Sh37SCbmbGQDj3K9pb7bL/sJSUds28jayqzi68ir9Z4rfq415TT+dh1iKG+s+T3ciUXsR+8f+0xwfqgUHaYH9qYevUPj5ulYCB08QHZN/9uZGV4d/gYoCD+SjYdH9CtGjqnJndpDPp23rBxOfukgGsHgfTxHQNgNuwHbloRit+oM8h3vpnPfHSv7aPph68AeZ/mMemdddR44zPNAmnKqc=
    username: AgAuc4pX6vE2zR8G5DI57wO0ToAGCc+loic6Xz9u2C5vIKJMcWXNj5NueNIPG4EDLpRjl61nCml8etBW4RIMrvKvxkWzj8CPCvj/FwLAGFqMYyhv6nB0Q8a1nrxs3PzwOaZyvUd2k7fnRcBAO3694vY4IY0cWZP+UArHGbXNn1C2n1C+xfEzNV2nMY0rbwbkkRfmnxG3ENqH4Jqk80R+nHa19x16GkSL4rgeM/ER7ewAcvjohkiphf93tO36RwHxcGp6ooYf7eeOV6MOI0ozOwJAmSK6yyq/ixklWQNqnlAHKRvLvnYOqQfUjqbAoa6WH05u1UBs+3wUCB6+K2YVihj3uxKkt8I17C+Lm8ew9hZpEDPkrPghOF1cR55fccJ5aRmYoJYuJueDAu2J/YlxbyYylSyXAMKVv1wZz6u0/puFRh9hGNUE8j0ErK7Faw747DVLb9U8udW9zLyWoB6VOguzYkk0Zd4ejkzOT4QVN5rALLmM02wrq0ifHBZOggarFS52hfDhhnKi/QiIbXgtyn4ZYzfZohbwZcSjb+4g/RFdmo1lz9Eb/CpSka5Rib6yAtfg1LrubGduG5OP1efaurjoZQHPF1SlBoRIh0hkwgMJDS6lJJ5gErgr6MfGV3bHRQLVZDfvPLA9tMoiuE+yKOG4WYKQltIfXWl9n4uLywER601LAXy6BWYWTp35nFo5Cds8YXWpRg==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
