---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgA4Q4tXu86OecPQ9bF/UNMQRbp0SfaOTx5L5CCOhOVzoRyFk+pf9DJl2OivmaGPdQ6bvSK4WeiPri73lJTDVkqHojearg/ywDZ03LrIk6jqcSpMD0OL73YIJMv1DoVaDeFaIv1wDwpCvoCWwwmXyTXjclSyIVykUaZXfcVZ8j8sPhXE03IK4Si7ntfDj9Z/MArPgKtqbg7c+uLxTUppPP0dDPz0fX6WSN7gpweAFdRPPdK1nhs+xV6oBGGocTf5w/kbFnWJS9xGejx3wxtUn+GI0v3FAIVVXJ2jLG4iauqtjvPAu/X4Ozo/MpVDtOYpclm+yR2ib8Pwq4TCElHLz+u+g+mAzBr3Z6qhS6PMbVRJx7W5zaw5hEkvHkrg8wmrHL/fpbYsLYNGV0Z6vQHeZFaeiDWIUO9w+W8HPg92dCIrta5U0lRpJReKp5U1WttUH7ROOetvW2faYrWT5n/6ts7R61w0IeovsE29336XzBYlEHM187mCVib294LeEr+714JNH3gF2WNsvBI85uZHLvZe94nFzwsbzIbYZ8dYBmKiscHmYfZJCVuvyevIpIVjMSHFeGKf0KgLc7xE3H6jswFlF+lGnVD4/jfr78fXvQfVx7VsrNy7cfZeosezL84gnxLehlMmC1mWK9bOK47qtl5KQ1Q6bML1K3fKCHFIdi6KK3yQe8IlWw6uGww1iatk6Mx08OV/xxQbqhgyDmiNy74WwjmyqPdkZEV1ZWwYnRnL87rNVeyQewEvJ7HHejp/IcRltExSPKJgxfT/iCxW54bh9CqF0ne/ps6MIKHw1zDbLg1ffyQ5OH2BXd9/ynM=
    username: AgCsoR33pFwYkDQAgxCc42O/UQ0DqkZ89qa2LBsFp/vTBgwSXoGQ8iAATiBldpREOiIq0X7E76sWBJvPOh54uw/gOBMsxWFY6ffRlx3rv1BogzUU0Lgyo1KKSFxV7dCBtp06k2pqI2GqqWvNckuLoBjsrLlEMwV+Xee+5duu5DeXIq/dNUFmY2m4lcfaHfTXQViAJpeEXEdQL++ortoC8owlab0TfnCREFeMJiWLiH/T1nvQQVsQ6VP9BxpkJA/xKwNPpYiJSZqEADht6s+y4rrIgsm8m/qECoOfvLEjDuv2uLtQTooDeyS0J9XQdhe5FQ4HphQWU5A2aKlZCvS4XVOFhw7AOLSPSoPZ98HcKgzQrxQhrrhb/3BzaP6hZVz05n1Y4yhz/ApSxzKRGHyCppENR8jA1DRyA+5giSGfNA5ktO9WTVKDjjmfY1EFop1pUKPp+MOMcexiv/+jqTSwpEiBqO6IrMYlynqIUINNfSlW0RjP/S++Vs6G7m0VHlS+hHl3RFyxdN9MYN8LBm66SqkuLuPN1TSGXGVTGxc2y+0oZBcoxQtRV9zKAXs31rQTV7a5KbvX/yCsyPDbF8SA9KzhwOmgdARmfI/l2GeaiCE0qNTLcBov34bJQKyjgjAAESl8f7fr1kBLBjc2lfKd7gZfvxMdS8XiEUz7qftzw8wcA0SfF7+SPvwFR+afxqWXe2a3y1AvxQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
