---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgCB6aKvocqMpUwn1YOE4KvxYYRMnwRVhD232S6/dqW8b/b00LtL40YgnqhI8lYiQt1CgGcAViJNgVIumOlpu/kAAYv7auGgYDRU8bSWBbdj94Eudu4akuB32VsY1PlCfEWEFuoBUxir1PQ4GVkby5XTvn452lBUMMVARDgSz06TaCkRppSjOnpww5RjrDTq7PS6N9am9HWUOovF891gE+q9Lz4TzyGSPAqWXMV5aZQVqTuPZFoDIKMdWlySWlN4XgkzndBMFo8IUI34xk5Ru+HD+ShDfjUupVIElaVSNWWRMbk4bAsovKc8Y4XcPqGhKQjMuXfj99Jl3wrKgv+1G8CfmuA3mqlan/CMXIOw2IolnEp71icbwbCFLVm5dJ8eUZ8F4bLP0JGEogz3x+ufMjJVKXnu8Zi89a3W3CjoXbqL2+I8pLwWO8z57jUnvNxV9hwPVRONq/fF0/fyeINHuzjsHI7Ti2ZXW/Ee7ck5NhJED0mk/bIzva0Jh+3tUHwNxRUPvIacht3rueNPj7A2t9y+JwjQdygJLwEPITt/UHcrlsmFaPQdXtMjyxzp2Vc8P/cMjVqM3iC1vE83uzxYKNtuebkHGxH3Ne6FxuhG7ztmVz6XlYhX62PZlLZWQkMxErMz8UVSFLujAY+cP6q7bPVunRNsVkWxwfXr+aroUO1XYxYrVcjNfb8bf1mAWSYF3q2mCuL5VGCMyswHa5wQ7mTGUdY3QlNySGTBMSZ/esg/dbsTHYEfCEqq1soaGvZjmrs701ZO1vZzNlcDyLgCGuH6s9Y9BXQBpJhc6hOHlery7o01v8pWK4OVDhV7PuY=
    username: AgADD8dYJLjZTW6gwpms7Jydx9ChqiPhZsXjvsU41jk3IfHyd9J7IF4rHmehWOdkd+O6g/Dwt6HzCpY73rDs9jcSTg8ba4mqgaBd0Ot+9eSvXwgoiiA7rJq76PLyM8crrADlgkFU4x3NiGrtAOAkc1JemzbLm+WYCM2BudrdXw3jJ8Mq/9cBCDXYmsbhrQhVrmdQFxBUppseyupyiFAtPG02CY40hPbHahmaIqpngACKnYEX1tP4EKScAETsPmeD95/bmQ9KJtJ4XpAnYH9ttQKdOeh7vk8FeAquhF/tSCdRhjzR9SBoEakBcwumTWAr3Hj0AfIhJGA26gqNq/Xxj19dHiIQ3K/hoG1BJHQwPrK4J3z/JNEsAaQhdp+vCy8Qtfgq0EyPy02UscHLyqzm+ruU+e9QDFWHZU4PxnCwCgGGzqWJQ9e6H2mEwhVChbGC8LgX37BFL4faqwyTA8bMdSyTCYT5TO/DMP9EzYPPjl4OxrVMsYPz+EaXZFp7OFJQwdRaxWPmE2pBxnWSYsUlzzo/bkVhBkL18X332sf5qEOB4HZ9sujbivQ66yY/R+oipMl5izq5TFFcF3YFW9uojU4LOxHMz16rUCv/RBkvPclB55X5tXgFswaLAAtnuZZ/GJRMA0/FxrA7MlGGr7rr190/b7mksMgJaNcYtwKsa+JuSdIU75klpN7K9AxJHNkNceNp0ndAaw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
