---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBi1Mi0f5sP0AsKnkzEm963pQ4MjOjZFOnwIGkKPhdt0WzKsykHfiO4dEE4if3LicKRaNDiw3c7XSvVID6OELBf+JLIOL0FPA0s20dg6Zhg7VH8mPBcH+/y9+42vbQSlbHTFP0wAyQaAgSGlJaM9ZOCEDRQ1wWQqjkZcSK2S9Ur2wflS91do1nE3dh6Ef6h5oNbhv5TV2asR8Bz4ihTlYTPvixesmppvsMPpn8lirOmjkWiu/h/8I9E1mvakzI5D0NGggoRNrHjksHMEJhB36XzJdkYKfM8szWNYfFwlv1XXXQBCTmc05wUgO51fkiuJZJJhcoeMwMctIEreF3Y+yfsqSztQrNQ7C8HTN3nsE0jtw8ITPMWQ1s3pGnpxvLGSxCv8LOUHmhmVqa0hrYIA2QBgI61fflgG9KBfV9Uz0BXgDWU3xJ1cuMghKn31TP3pu/Q72E9szjDMr6CVhsbwDasZFiGkO9APUc1ylZmWcvabs+TJ+HFsC68pGMI3A172BxhWq7BIZy07KPdtJSv52KnHHh7Zf4NSGeafb3lG3WQYQQiaCt0IONh55leAC7U85s/KcfrtuBnGsCjJCiIpYarP5U24RO+5ur97Vxyqr9utHer2LuQADD6XjW5qX2zTLNDrzoda5nbnYZMCsADwRUUBdJ8T17vY/EGRwBjJdHaL/wxPbhyBpG72t98pCnQgxiQRaY/ScKAeMMTyuJXQvHLbGi6YurHhCRe96unjjMbUvG0mgJ4N7nXh6eDhNG5qP5B4mObydJQoljXheN5pXWeYvWqvFRZQW4n5ChrB9uG6Qhzw33nzGbCAocsxB8=
    username: AgBUnPBr98NpQ8m7NF50eNvC/CofZhOAr+HVnPM8G46UDGagpozKJkocbVMJrtz6MpzlWQB+I+sOX3lim0o52ZUjazG0u6C2BXFbWaK2mo2B0F+4Yj3+ijk4tqnRhQwYyRC9VXUj4ZCS0xvFNSCHOqAND6YXeQAF7WI6TBMS6ZYa67CWAc6iy2U4/96zcUwLPzYVWH0r72/Q2bDDSWv6l7f3jlZfX2UMhQXrkVX7C391sagh0R/1qMpi0Z3jWOF0G6z7KKFA4xb6PYz1g8nHzCvLwPEbzb2Rd48LXzN1sGOmk/HmaB9SSoN4mcU3XoaUYWt5IyekiMunAwqM8aIs5T2v5NwZe5nzrM5niRQjWw0GHBN9mEeqLbfSHuhbvDS9vLFAsGvBS5ZzFtdK22bQVPVs5mZ2bOYXOjJ4t7ukLMOyj0F14cmc4+AUcj1R93GI+MCiwlCGwdgveJhEAEXOGNW2ube6vCqmE1BcO1uO2/hjzW1jpTcUABYeRYVw8lp5zWdhA9tJhOeSLlZZMdurJK+AYWIeYNfimiEf6XMv6aPXKFtmShcAfV1B1FJZDmMbIqVIZEl0YIvOPWxxcYIoWqbh0/mlso0IFgbrCC5qZ1he1deF0BFOmz2RfFxX2yXKZ/DQ3IIlXCi5fcR4JbyEkKWkcpy3O0yFS0DNWtl0c0aXPKusSlP6Fza2/VDnKj95dYC9KKU2oQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
