---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBry/1sO2ogDJwycdfqfAD0/jgCFtsozVwWMimX+akBLeDhaokkzrxioaMqftzc8QU+HaydLzSaYmfda6N/A5tFvKP2dnwdDI2qu0i0S5YB1bSkPU/9VNarlypCEP6AgWf+IJ9to6IqLbi5kOtSzASl/BWTUKMb3AKHOx5Oe2a4Zx9XStRJWvXsZpCgd3KvtF0kwFwoqlpO6lLhYfp1Yjb3TZhpoP9HdL8R0/LI6ICbU0KJe5NTIE2x8Y/xeb77LKrGdrqm2uzMl/PqWJkJLwTi89iOdwVHtg3Bm4ngJlzpq0/1AymQrksYqmOYXR4s2Nq8pn6HC7/qNFJJed43UXNtWcGuaYJB/6oHLrBjWkn4C6wyMNbdQ1NsU9WhviKbs1ohmjGHtKopponcMalkOotAl5K5GaxzLOj713lUtVsD641/kAUgkJNDlq2ediOWq1234n6POKzd9N01K6wQIxksB/bgIBML3nbC2Zipw8UfligdBVVo4SsvybCkFHn3eq/GiAi99DzgOQD1wBduWJS8tmXgfENSDXaTAWAyY4+iKElFwhv+2dpLacYYYkByXp7VUYIac/kLyAckHhAyQfcvFOy1xSZwZb3K45DTWXxruK4GqVQfXsjO2GUs2R1zTEWIMHiW+DUp4qDXnMoQ06MwZCnklIARjcTZ5jRokg2x6q52l7dQD/1UVDcvzBIjV2kGBhqVN4EbryjMVP5eOwlfY0Q1BywIdGQ5eApTlkl8Rnk0wQ+BA8C3XI4jX8eIj+xGQh0+PcZOkop2ZefDsT1F/d32H9v0Qi+G/qI1wh47COsomMtHx2S6XQQ57MU=
    username: AgBECB02z/0N3S0krgb6mIhrmSeD0QXkzeJ4b0RHKfUd9C76IYX278zrzpFyZzirxW6AS0Pdn+Yjm3MsF7uZh2njgm7rmMMedwGnSfI3mVwQ0PD2m3pv9cFEGaUds4a2Arx+SwnxkkqviNxyHcGV6FjM8uNwtfmZGswoYkQIM6dh7Wgb0MSNPOqcDbdArkSdYRUbUtZDYYufDfFIjDnDIpbJVv8NdEtzm/AaG/aMdOjCrZG8jNFIO43BTTJx5poYlevjxsmkITssxsIWbpmgcjeDHaG6sL7rexjiNtkl/KecWq1zUCg1O3LTL3UnLxVgrj2rNOVfRdbbFpITeVA4GysNfOReNiErc/8ubgEVEE3YiXlG6mZHyr8fjqSF4W0hIoGgP9zj+u2x9MYCvhciRg7GjiiuBcaUju0LqJwBiB3mNb3MBz1coUwBujW1q2lCRcZcA+DpmBnEMGFWePffiJa+M8whkCuAl9ULmR+/CAWnkxnDIVv2uFQi/tPAIcEmCWVq/r8H+AhFfaPqpNuFbiNlRodLVghyPfLEE4XrJRASY2hhYh7g7mGxaIH3tNfpBCA23HTYuDbf21Hf8txsx5AqTOu8UHrXdiUEIUVQBeXSkmLyKtA5n/Usq4gqnOlbvhktKE8thZjRCOcVe6Pxp93Zo4YnyHAYocDYUthURbj/SrueHvwRZTXsy8N88voGPcwXOvJi4w==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
