---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgA4Xc0tvbrUU/gOQViketosYvfOAU1V+t6LO70kIxVDwLLnCAcejR6nZBsuFmXxazmov2s4E2otLoEQdROjt0ecTJyyvZVJJ0LeOEKXhM1lwcnfcLjt13Zh3xLJXY0iE3WPsxQSda328mxiVJPqvvQlfPQFDcwSsnhM0x1gzEf5QlrOMWth/qjAgGW6LQikZo1HC++S/8lH+RZUaUGhuZMqa2noWMYt5F2fe0NbhF0N0ADF7YmCU/6/LUtpv+DUA3mbXNa54+nHgrVTX/xnNKO8w0hTVsFFFOgj//3kptCGRBRHNLc9V6v1kQMnwa4FjeDnAsrmWWRzgmxHUuLmBfYXKQdkDSwZS0xYBoyXOFelZu/RGh2/2d4eWf7+8QhWqv8CACVmF0NEsLAQ2JSepOv/OTQb3mOhzzTx+EM7hjhyhXD4ELcBVk934W5MBN0M5A9JqftmNqYqIHD+AeFZRutxQsVlXFAjb+aTKfa5wX68b6v7F2t+m6F56lLWomdIffpsJhEr3TJhC8qiKmCJqI3k8fRGR7MuLKmXWifFuf4qFuBeDPU+LLyDKhVleEdwLYediy/1rhyfzD5nwonkw/jTz83VHWwE4aH9zb6e5tbfL8Zzwiyx0vOVQynk6b86AJev/e3zEog3rToopBbW24EW18tofZApQsAVbuwTosPnLshZVbfPvihEcpnntRL5Bdki+q+ezzpL6rlUAhhRqwvxzpCqgFN8QsPxd7L5G1ab7YsDMnIMvJ7Qtn50Yl2ZJ2zpLtQ5FTB/C5PsJD8nx6IA7Uh4i0CzFbR21rDaEJ6gjL0MeERzod3aCztGVyw=
    username: AgBakSWLRlNBlWFEbcXGQPtEi5Y/atWLYTfydGz3Nfvgshlovxt0weqzKRjg6FOboKnPoqaEYBahCOeuC6Vcqd2QQi5KnuNxDoJaZTcpVjwDi/r6RZ//mgNTZcRYXYhfa2fDp0uBZYxjjPwagwcd7/TtftakuEjS0R8/0bwcejsbEY9YNNUgALBrtC/a+alGY6BqqV53yPKfzkPnJ+sZids5CEbp0yTPhRCKBzDdoUys6veLx04LhTs/ubKzJBC9/QOM6RZdJY8LGa8mva1rrT4OgZW1t31NVj5F7bvovAjDO76iaxm3ZIupz1UOaK/amWu2HY5VGu+VcQGG2X4F/hGnR0hw6ocWHei4qTy8BgApORaHS/I2yBKTsqAEMhZJdxwyrX1QRn5hKpUPA18YFjOMaXvbOLU3Z6PjoETxQ2pk0xFxD8VbJ7wT81Gqi+DpCdihAP4v/FM+a3xUfp+m6Mq6ExJKr6tlkIlDNj/3d+TYqMtZ+uPnUWwogVuS4oLrHfviduJ7Epada2O8pHO70Fm6rZruAwAKTQdc4KSM31JGpXwHVkBreZCvv9a1qMzuky1GDFV9nUnj3sLD4e9c5U96zjjFVfbOxaUnENt9ti7UrOiOA+G78y0CrFU7rK7dXw0MXVlZunGw2wGhniucbe+59ONjSkYLJJXb2W35qBOT6oUy5VsrCqrF9gwadrC5QYDLIBLRxw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
