---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBTHBboOAKe5NRr0nRne+CQjFN60DIkYEFt5quYai5pCgWx0F29H8harLwPeWSrDMkYOSETlOnAd+xmOO6i3JtmpcJIqfHB0tk7B7VOP+9ihYF8NbBzdXnZiNO2UllydCUBY4BltdXD+VysxOu+9pFtRg+kqbVX16hhRHkrnQrhSv6HWsW8B1SjNTMv0bZm1MtUhYyIQm1S77LE8B6zmgW1xXPnZiI3AODMpgjka3ZmLIjZYnoJYrBsHmt6du5kFVYBhIEh9nmr6BUnpe0mijb+0SAOTp6lGmOHrySYwrXOixfhSwc93/8XLAdZxs9rryo4tUCSLXpSk1yG1FSM+vGskWaOZA/fe2bal+EZ066EfGOFiWPzQaVOnHAU3HpSR3LRpz3qz6XUOtyMM6QCaoRHSlM/86bH/inCKddTkCl2Gpi3xGKLgDthmzJZkFN6agsHoM5iudh3TULCZvESyqyNNom2i3OGJuzKNP9Cqarfxlr3pNbBqUNpB4ps3L2zymtFvzmiPvRdIDvmSfN+XtA2hAwNAKpmitD5gQGA8mWarlMTl/TebNGPsfEyLD6qaJRL9xQCxLvC5+LjaP5z6s6pEFehqKfWy4V9USpcRi8J5if1VczCK1wom6ik+V47CTkCQPU+Q2qy5cl/wALCWIXSe/vMMZHe4B+HGninXXhVsp+N26cGrxQBZ6fdfGIh1vHV+RW/DXftdqOh9RqOS1dHoR3YLsSks6gu+pywq5JIZ/r/1igxOCE5Z5HQEH9kvwCZtTe0ZdRuUL9cbFJPKktgKiqWJECNwqDh9L5SLWwOEhZ6hCRaKPDhQtRQusM=
    username: AgBveZEgoRcNuY8ncqKcDkmpHodS/v9jvy59Gr4Q6FEXq032ABKq0p6m8Y7Jva2pyPHMq0zbd9kWcT7AS2lUgdzKJwRvgopZCFBQkUoQKlhLXte0ouBg/R/OytX455NfN0cr3L5spK9UUMuewPssm8YULYy3RQhpgafUwPI5nap5/KeDrNrLMScxXmot0OWjUnlcl5fXZjcitt6bu3fi+WKN57StH5JRln4hzRhraL+hepe5Is9lOHuHlN62QthlCr1OrOj6jB4XRvYERSvRmO+Q28ZfMu3Ol6A/Fo2DXlkdbrTiOX4DnD8H3Wk0E4Osnr2J3qQGyn+UfYsOyGTtkm+dMWG/JUNkSduKXq06z0+RmmS808k4+jpz5POCCitUzFdC7buskJhGZZQbVKQ7iT/oHJnio4SlNxCVBm7dlZvUbcurwIWaNju+uZKS+WWrcxF+OCU8mkLEOAkPKPAE1c7uzJn+a93TZJNC4PHhi6WC4FD079v0cJxlRh5HXazsXbOX8FWpJlfDU1Q6tZ4TGdfAMbvAagc/yjBbYH8tSDSVl/iXAo/LRxU7ll7DcGuCm3QOd3ciRZAqJkjJ0laZdNvOabOiWkpODxHHM80hm7XUt4ram0XsYEfaM3/mQmIJpL49AZo5lKDEB0YrhDgGNYwtC9EX/bNH0XcL10iu75tiohZVNuooqHYNFT9lWa06CTzfWHZDdQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
