---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgBazcdJaeTfYsrPelrZTR3V6/LWvg8RUbCPI0uqm0a6l3u9b3C9sAN1GF24qmJfRVdiNpB9PrQ+6iQMVbNwmezTktPXWFB1bJTiv0rMwV7y0YIfMiTFpK1ZRIWJQzRWCTuJ4aJyjIvFhX/FP9WArF/CS6Cu7eVw1u028Ptoo7+4DfCtiymXgzDEXFsjML2MK6NxONYQ46bngKSS8AoFoQ9xnCGwtyDDPsrQh0928uePfXrPHhSlkTjtum7nB2V5KAIXCwtyEPgb6QE8hoW5T1n+mkHWADL3QCnbUfqPNy9kA0uoBFk2fNNEEo7b5kwYFzIXrEexjmJA/9NfESnlYx6FuEDtuVS5dlKGGEpWXwYxqCnmfFkBkus8+fDlPhJzr7BNoKMqWql9W0mK/nbkv0S+GrFdhpcmBpx2227gL8FqU/8KE1/UOHoEA7eLT/epgNSeL+HEElD5KK7VULoNnH/pTiC7bU2V1YMjUGRCgQdmLCiAesFxO20j7fmSyz6DPHMl2xwvuEZ6nwWGWQXpbTy6TK4gBj2diwK6+w9qlo+onPiEN1NV2J6BbgpW3z9izmES7idYvxTPVAwgwgyZCwlTTVL+/1EH9lcJZ3aG2/o0B7oC3uXOY0qCPJmSsenlglXPOPCI47vr5sh0nJKrnjh1FIKIKf/1Uu6W8/DMBa22zHCn+Bt+GHUQLbnp5B/DsCaNnqtKwk67woq1eznL1q8FrZEjqf8rRxrGUbR3stNYQua56ODT3Xw1mgWsuvBZj/2rnXyfcR+gYGikRr3tpKkCJyCr7knBrjeuUuWJP0EKSGfwrYSQFtOkVgoE1i4=
    username: AgCRlRZBfGjK2cYApkn2zmU2EceHhW6vb1NbaqWq70wtUzf8Y/wmpN69hbEn13riF4ROhbp1QBwA3rkUiJaELRTLMRtUZIfVmrtm4LETw15uyxl2cjjiFDeIXLgYU8BqgYSlOaxbjhxnScqy9mgNzKgNO5M/4LQWF5hdvEy2N2xJ0GMWZut/WQOhdmICIjjphLOrQMJb+DjEkjnoMJz/VdCnzP7bcyMGVYeceljghj7v7vW0Ae+WClCyynFdd31ypj1gL9B09r870+1fLEDiOZ+a9aWWlD6TkmhJQ5e19KxXFpxylCd5KdBpSniikWlXue0CZ+G2sNntvQA5aVH5wK8iFu/WsWNKZrDgEE31q+cFywjh4TyFZ7dHa4agkSeajWQa0w8Zzyh50n51kLmmNAgIKi1aXkBwpsch5aHN4mI2su7fyq1qn/hjcFTn4SFbeXmIKdp3wZ8HljhIL0XLx9RMRZvVGmZS89s5+5R3QIr1rthCoYDRBZdjmkPnup8XYIf88J/UCK0QZgVcAd/Lt/qwwjEozFqtsa7yK9VEZqbbd6tAxUT9TEWamt8BZrsPmVberzWwtcTtgmWo8qVelN7fxDljSd0oZt5t36Q4A5LUgnlGxzmOlzGvQJkUIKf75u4ZmNT1NNVqlWfKkxUaSPg66M9iJ8A62GSiVtj5Dj11N8ARsqV7FA5IsLAU/Z+X5wEC8J2nuA==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
