---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAg2TOxfN8vqyS1ETa5UQNMRlBjjbQaym3b+TXUPJQFSJWeUCqnUPUkuHw5RtDb7B3ZVesEMLHiLgK7OIhvgDwklbeE1a1QA8xKAzfbGu6facZnYaRyYsYDC4DukzV2frpbhkICdrKhUnPl1PMt6yHZM4JFuAmfuyHUpzOnNvvm43JifNUYtEoQ+Juw8cmpKfzejd9XoeraMGmckWSI1UDNa7rKj7wwu/+preQzetFEOh3hqVnAiSvza0h0TPpW3DoesPbUinuJyrzHeAH4ua2tdRFP7zg0k5cxx5LH59CCUnSgONqbk0Nbe06WFoB7mrHw4qZbOzJdXgvdFrNA4qi+lFfrW3fxACknkvA1vfZmX5P08dX9oEiisp42iuTVq9uzK8TgsIpQBJkBOIOMUgZ/jb7lnTRhzOsNzCX202BccKt250VMnhjj+HB/0QlCeNR1lCbYq2bCkur13a4TO4jnz0FHKp21ODEdSyV6vxiHRDnrvfvqmNcC5A8c1ovJnVjZBHzzcpn97A1pkfE91qeK4FjsS6QWq8DhFQePKqmhee+PdEaAyeRMbfdexzrcVjbxk9WcWaz6BNws4YK89wiQAeK+amYzqnZdsKFlqFKj+YnhOMko5PEB4iKvi3U3U9oWjT/ygpvJCm51hCW9WA73VjEQfmu+mMSM40X6AnUOLxJt0YwXZNjCP9pDFMy0dDbEJdVTRO5LBbxZInM9WWguiFHlPy1zGp8KAp+F+adB37gsK1NzCnIpP1gFWEqO+Oo9cGfz26coCwkSA0w0eJ5EtRFcld0QoNcqwfeUjwtuSAFrLjQfuVNNxcRYYUY=
    username: AgDBjsXaB8M9SqVOrCoZZ0FHy72kA1BYzVNCtWMLIX9w1auNhemxKCmtfiqpyBg26dQ9iDRKvN9DzSrnn06lsMuAdSlU5l5yy9L45CCzWTI8tnJ6t9aT4sckuy0Y/hTNAXGcOTJrzDWpsU63LgdW0F8ICytxg3ij7cgqsdxD5OABzfPLNOZpWwSzTjMFV84rZtjfKC/REnoPNWY6AFzhfg+1AjvK8yFHW/l9xAboY6BqzP3l9VYRVzKnPoGmtze5FazQT19mgTgwfQx8l5pB8vJqIX45ZPSQkI/o5CBF5glv2oAnRD6B1Dz8/D1uzvE7eYg2UI1IO2z135cSmZGMQlwD4rVouwcQPAidiVo6cujAHYiUi7HXXK+BEgIBFBPRNO2TMy6GuyHaFbGBlElCn4VsbsFIWEuhKSbzlYm4SwzGSPx4tKgZ9mAFCCatZNbUu1nU739ahFLRqGQlCLM+amC8A3quAkwgo++zHTCmGQdiqJubvtWs3p/UNt5iVYM5Dpti3H1utMyHgunLfDqJIq+BnvS52KF2r88Dstrg2PbJ1xz5XTgAxgglYD6pGn8HhFO6jw7iFVpvCfEUL3jVI6nGU4jMwdjKGNapz6tjchbQJM547GC/h/oSPmlD91hZuvNMho4/1S8EKyph08XMgIQWUl1Z+3j3U71TZnWiaXmZgcswQnSqRHqeH8q1MoX9p7u6OQIWOA==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
