---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgB8niOiEFXMjlcwEkLVqEM2/KrLo67HyIqzWf9oa8f3R8qcTuurBWK9KeAmkwT3h5l4ObwTujuWF5FP6vhFXUKH9cDYSW+FFsZjlVXeNRS3YgjfVq2NyG3tgLXieC6N8j5m5YeTMmjXw7MKaisvo3b4v1hGg3HpJjWpuH7zrxyZwykvw3HXUg/vwzjauD71+PEDLJoxjqQ2xweaoA494v7wVrtWhxOWgSYwcCWrFOLD9UA4HISmxL66PgaPjzsStwKnvWAylT94hJ36AVsb2wIrNv9DC3Hv0Tk22xgdH/aIjG6JYP5agbq2+7Y5LU/yfgca6qq0s1+d9iO3Jyi88qZZdOD0z4B3cDHct4UXS1zJ5nAppwvA7/56lCUDqL20V8EcuxfvppXZonf1xJq9wNn4blx1PlCySl/UVUJ3eA1HAr6zFdTfAmZhRc9cu+6tXOZGNyMvlejRgx5Y6/mv6O2xQIPRsTEsyVbCTS1xOsDLnlAta3zxzzkE2VELnGG+vVUHKZdDNuvlnC6rPtQf0wJjgplDZ3Bym4MWqosy9ny6jC2HBmkWShF+QMepdmqFnxxRrEUiGObSEMKO2VjMqnAoyAyS1OujygkKFPJ/NxZrn0uVLFUNRwlHESYNAgN9qBCLylqXXEEaRNDouo+JL7qR35BBuLpn4Gm5MR5t24SKC1RrsBsFySXHic1xGG4HWhXBjVBnFg4B20hZpY4NN4XwAC/hi79hbM6kbjco2OpXtgO1AcO8O7GMnAMPGU+BDBzO2MDvD4WBZc8jwrInyVHeEdH3zZynpiIgsZql1LUEvyrNxhB6zD6wtu9AK9U=
    username: AgBGuxifZi0ZQjfElmBN4ExVxisolJLQdVBM8gCFVwXa9NBbFrsk+9bZFuPCWYsNLCzeFP2ELe9YxsJsrN7egJ+Y/pUj5jbkSM0D5ZUYMeIc6sgjdUT1SRJH4Ey97EQrqBs73E0pgDNG5ebacP1VoFQvP4io3GxVS9JBosdfS1iN340V3Cjh8UU/VAwEJ1bF5UVenMwreuRNdDCDDnINXxCEgtZCLAXhbDxdApgdNjIgyr1Xr9ui/wOGCDFi2OnbDISZrCdfT8t+y1NPxnosX/2mDGHvqkaeDd/gWiuLTOGsKZpFDbCXdyJYnAiGQCNv4jndmbZu2VY6pj3EMeZ8fZaCDx4/EzY6DBlGq7PN/NvrQWBOeQVPsLdYFX4nVVXDtm1zQ0d0jgLarP2pHbGh7rboOQVoygVMgI+eKbcG/itKVIMSF+bgOO6Hx3EswXUeYDb00O4IjkXtWXklPRMQCWS9qzroKmVLDocR3cmq0ueLQp64+HnYLO64HZ/3hPVhuKsPBga9lsuhi/lSSrF29iCbcHrNr5HS3y1yCt9tHRqNEYsWQKxEVmvKKPOYyRO1DGqMhfhYMrGDsf0FDdHoWqRDSxXn/aMhfAKoZaFGBqZuqMg++RA0hj2J9MMAIZKRj5hC9GpNizEa/+G4LS9w1O1lXVZhQzmjctK1crBSGNjDrAH0Kn3IgXrfED8aqvFBbsk6TxVHpQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
