---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgCW+hyawiE0cT9obxGvbWGPv04Y2AaeqlptSUzdyof6z3v19UqXVlzYtYu3xI1WqXYI4ZHNRJqzKVxUI7zv9TCbtHOzBF+/hNLThjOE4ak+Hl/2GZU3MPGm/N8FW37rWBDF2pab4tXnwv7G/IxBObvrsJRxNvuivObzY60eE/LGGJkw7TcdOcIQU5IuVqQQ0gnxG9nR5P/hhmYWeI2nayFGHD5mlGOs0x2rp3mH5sirGlyVWSlj+X1SWcAp5KqmpywxGTDwssnQLG8wKt9ZQ+hk6hPkFKUqZXPJ0YkGqJ+GottwDEVEBzPa8ZC6g5i0rMzyiLetiCudptP4fHesveINjhMBil+wqWhI04um/d88bOwl3J7TxFMFzwvloPiJpxdkCytyshkN2jT0D4sauSFhlwE8p+Be8pdgLWXobUSZBopf12UDNS8WtLNc+hrE5YMuCHPbGcwzCLaKbzYov0FYPMvBYWyO0mEZ4rxhiWSJ0sP/519T+XOcs3FWw/AyUWP21okvXx/uGfqgl+5KL5ZyBfiocT3eZntpFuoqpUxQLVLhlHwf1O189JvlW9V3b6By8bDTL+yZ1HNXzvnHQyc/xCRnowBFkycGY6pTB0NHRW7pcSw+7GXPJWmj+vIT/KxVsj5iIxiC7lDch222RsF4aJ2tENrxpZxpmFWR6c3q8saSar2EReLAr3tgBI+pnqjHjO69JoIZw1jrNrogfDag5qa+4ENGsiNAN+Rx8lAARbX+gtvKHssa54HGLvJ7GbpLyvnzRfyfgJ0ZTDudgeXiBkK9u21Ha4KXPR+N4mKbxjkDr5ogGpHxLRAlG2U=
    username: AgCXlnao4+4HbpGOHzdZ/qbF7cuvWBP8m8MqDqP1I3K9SLyuIhrLpQQwFkDzVg7jsfd02QcvLzAEaGKGEQ/5Ii+CUdEotFW5FWxNrYXtf5HgUVmWjPnNuPuJM6y9RWUGkN+56fv1zAo45uximtyX1JjjeCDclYy2iIwBWPGCeYBAsFIryVRIhQz8h8ZticQ9xtjSFQlojzqEZV8S8HJFAS7ZYFOlbZwjlVYzrjkN/j5a9xkyKFKVmy+aok5RiFj3L9BhKw0/4K6Z77KIHDQWlKLJs3Hhx4XNHzs5N8ijGCIOznCfy57IbNrgQS6UKQYeMQdyLrP54++T+aN6etRcKPjVE1N6nhIwMHBCJ13wkIDG9QJJzezHuqM1jXt6fZBuF1pizpafTk5PBqJKsFJa8alIZQ8r7k/mPiNiAlDPelh2olRws4rE+Z9g3igJG7sv/9mtqyZrz0Pgs2ZUAnmKiclRzJktGEfb0koXSqRmJgpMZhk2g8WGKiC5ZACS4q7LvgCE8ASB6cw8AkkXqUxvzFHXYDPLGNgedle4oMHSGtx3CP2cpgmtGwytwKMZYVK8KMo8tkABBVFYeRA8QQrsldupZr0xu2Su/Kt6andbmp8SRgNN8ECS73Sr1Fks0mIDSsNSGP2dsZCQottI7AICok3qN+fiwN/DO1nNWZg07wyJinViwPtQD5b6wEXDW65W0C2ozQbfrg==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
