---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAvSVY4hTxyl5MnNOhkHNwJfqqG+K49qu4fJQdtsDPHHNyvbmRwGsQ0g8dy3nF/5k3MYRIcGChgiqVjhFTuoTIP1zDIrnHjNL4R0QGER6ToFth0MtsiwDQd6X1S31E3j2x6+2S1xvoWAfdP7yhN6DxI7LzThRk/3UjLsh4QA4LD4R2x+qO52MPe/QhkjxEimyqDLaT8J0EWGvBC74dMgKCAKFFU8ZPoRvKqfHz2gVx6tRSPFX2Lxmb2Defs7cr8nFJF6MI5ixr+mzEFEf7MYvfIa4XZ/c+wzMByAUaIlHNEhmhxp+jXgwX8fjIHwZLC0aA/TVrY0JkWNEdUc+VNg36lDqaRyC5zq3PFa+mCfW5yX1bvUk7LW76kVaHgMK0RxyvxNwgHGKLxchdEJHJbciJqRUU7OKN1vrM1gOMH/VxzxSgwhogUz5i3ccUzZ/ayx6A1DsIq0SuRZKiyGyIqnYkRvAs9TfS/otUrx/YhqTXRiGIX0f5zApLoMoSno8yMtnQaiwM0uK3IbW5ZzrSVKBdShteQO0iOacbOvB/c+0+9tHEdiz3uYE3sFNuNlCtySnueFkmDEbV2M0GQ5EILO24Wxyz9uJocAGcHVAWNZcc0AfMKDaQ0Y75K447Lc1vCByI9yZau64iehhwUCDC9hb0MKKXr3HQ/ggLW7x3xKd0zD2LLkKjLRefS3U0ihlb/1QSLBM5ZLM9r6zHNqTxbdQjEgqfoktMZJgVAvqu4uT2IF6DaiVhLTKc8DkxsraepygaG+JT7XscEdo9eH7rornbbFUXI97ZI2qlwYBAHe+8vc78zLzkdQgg/CFjh7lA=
    username: AgA4wGhHTzll3rsvGxWAdK+TaNGwweTkjb1aYmZc0OaUc379JETfM/JRuAaeu6rOTYoTV2MnmSNHtEdK83Ea8n+TPHT1WrCr6/dndC3hn2oTjLFsLhtQ00oGOZ47CRR6s5RibrMBoh0PnQmANlt0xP5WgiPhADiapFO54OaDZyn5FKmSR/be9zsolHGJ4IvC/JBdk19RQ8AAeIoW96YmitevY+udICVbaSHTyTQbPR/KR0PrzS2sm7jCvntc/66J64AI2p4BuiweEr96MDdGW0w6TNgu0KEcy18+01PDHSGOKlt0y4p9nZuKBudvdqY8pvk/WSmBYCJBJB41pDh795Q0Dqp5sd0CzFp7Y1VDmB1WFm0FEXOu6BtkmeLz7ufOGl98wndxk5HG2I3GFX8M3J8RzLPJRKXOvMMdspbIxB//kaDanNlzBSGLupr9EpdWkHRp9SorKyhp79JFiQGLHtrVOGniBcU3YM3eaGjlXRbmt1wYsJlSuz/RgePH6L82pyfqyFPUXi8otoprKIw+OrXfMlbbaT83y9/feVSN5+Qe6uGNXNfkUJhRAVW+Zve76wjuMVvXTIP+P2mTyjywi6NtjiVrwbviDWQOaYXRLjNnkC2OPV7OMOF6b3msBIM/j9isDjLvlG6tf9V9cXwJBtfPUZY2zPZkO8GkqwLDeHy15zFzznq99S98nszGfhNCeaEATKgWzw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
