---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgCwuybWkpFfjCntscTWELjOabYPZXt9QzK39f/ihJLKYAaodBw4LidiR1FlumMQ3CxFc4k4LAEzVv8+nVbK5MuzaM+QLL5oBP+wr4TrDhVH8Z/pmEYIjDslxhz0FjuhI7WvrIn94//ymh94Wazg9ZU9McmeNkJtidPA8IYjXaey4H0s+mjztGQXDPtUYN9j1z9xnBi+f8TqjyCr/Ob/XpbrKE2U6aIcSRXGLYE0r6IwrbCIMJS8Mj0R00ZGbguytDh4la1/lScA89dXI1OXgVRZj6KD54Su989bCk7feRSkp/c6GBYK+g3cuwHNpcW2pNlSmT4e8dUJvoku5K5A6HEvmziA4R6eID6UHHnFeD1MJ/lRVHzmEKgdJisM1yXMajmkup2dFBLgiZtqlNwjQ/BsJ0LLTk+o9rNwEXbe/4Q1VpEXpEjDEBpCil/7B+NAZ6HZi+Ho0aq8QOi7sbZ3BSPck61ewBPDrbm+jAsJX7O4oEFXnppGfPFBUB4p3BWUXfu/+waFfmVwwdoCvo1Z9wyDxUaDawCFjJlzqncPNiFpef9vnW/MXbBN0rXoGRv7JB1AuNg9GOcFfPEPPpAjC8r9CG0WBtQUYsZzjpRfitu55KxsYi0Km8doX+8Vuf7yMGbYSJEE9Hvzey6cLM5WyLnZy+6QOMquxCe4yBafVZhgyMvlayd03HgCVus7HWOvU3wRlxfNbdyQMz6RZxAuqFnz+K7qUGtybJeWBsUnevOjmptU2t+gCzIm7kSHJoQTzOMGISLoQlcoj16NvdHleo8381q6S2aROunWG6OgWAOwjpqQuWyfOCmx7MpMR/Y=
    username: AgAO/VieZTsF66kYKw2fS7+3gZBJoPkjonjdgG7rmZvV98MlkdsCJokp3LthTifBO+feFqOHS5f+NYTIsw9n7bT4a49XMbh9PApoxa0MfRRwGzmBff6QR9YgOrbZtp4ADMwduQWuN+UMCxIZJ+47bCSSbaNnjyHa4CGyTyQnYNhHSQ23EY1bmZ0oNSRDnhD7bvz8miAHgOvEQTt9z1ek1MWtKOZJjSF2yrBvm0vBYbBMTOhXBS9+vvgTtD0GMHkh8KKUDOL2WzAzHj4C8py8eec76vGzotDC0ku8F7CIHdiEh0E2l+ujCO67vYLW1OcqAab+J2u8RaPk9Yv9JaGtU8vm/8uzN5dXFzCeuTiTXknRQr0o9zptK5R6OWFb6ZE63lAcK8LBGs5M6uUflYllEfqqFgIqmp/Gh5YUrrDk1dZzIFbl1JrTAsWiCJE47P35x6//dNFHJGcl4Nm72GQrAz1Humv1RXz6G3YadQYMD3o6TnaCQwKLvFK2E6+iP2DG94lEosb82YxNZ1klVX6PZFog4GBZxwzrcslLzN6Zq6xz2pArZc3vAbSZO2PXe2HYlgH70c0wG55zC8h6z06lT47A8F5+l1IiKszgcjUpM9Ug/QdGktnLschRG4CZdwt+seSbYt6lI20A9qxRdzZSCS553hwwUWUd7yXIwLUgdg/94edHbWHqvFuWaN6Ycbwj/OsiDHH7xw==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
