---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAu8wlpEQX2DjcIqz7y67dd11b87GkOGRD5wncpoBZ0N0cioOODq7o8Ko7IHhm49qyvUVUw8Fpa5IMLlWi5ZAd13KHzTaOYFm8x4LI0DF8HuTePt3rTML6UUI8kUwftMMabcM0fzijRcUMT81MPg3TjR0R4pBqlWZBz1j5g14vEdtF7SQci0hOZXUfs3N+5a4Zy1iX1OmupHEulHt6xOJw5bUyiR1JD7+u/+rHqimBnRdWKEXm8jZv/ST7j+dKwKByL22WMACHjhno0zyRkMxqZ9dWk5Ury171WRh49DTHB13mYApycayTu2dh6gEt2cbTL9w8fm+FufDJO6Pu/IV73/XkiBTJbCjJTCqpXjRhRJIohidSNZ0cWNaxQf/A1rfUXJkA1kdtBlQ0QFeJuI3fQErjp5xBfJOIr5t3rzk86qd+T8ZMpxfaN3khRJc/Hs5b2LGpcxrSwyQt3sqbfjRsHxzSEXaHCxAaejXIcOkTOPyiSFVXDEPObgj93vHCHRWfypYFiO2zRySRDf/sV0qbs3kw9oFx7GqTQbQgL88Zgp9TXOdU1iafwr4fDUD/OydMOFdiBa74FspECqgRFQxywylrJXJRPvn4yY5Nzl+QmzfoE9JQcMvsdH29IG9pal52ZEQ/saionmNtQhJ8wXvosLqNitxo6Lu7XM32Q/9CWgc5ok6dGFds5ptxQ65HRO4OIVFmC5w85HZo8w8d0AON/vJ7dXYDo8IABCUmbeKbZMYhwunRlws95/4VO840Afkh18hYzABFlQgpxrL+bYaJ/QfS8cVILHpaVPvp1NwTWWPFeT+2Lcv7Aa8nt9U4=
    username: AgAOlpSzK9gJpKqYJvqqgI6PA9eZ6FadU7g8SZXgtFVfWM1FiE58HzV99RcZqxtcyvvRK9PyruWxEL1FGFjlnr9xvN3BkFxuBBhaIMijDC19kSkpi1Iyv5OwgVG4V+71Tzb3PfV7xWH7ZYjDEpIEadrQnfylBhjZxGdaAdRwEbnIWljct4reXA475S9coQw7caNlh3FFTXGi2ttrgtx0RsLKX1TaP/LhzDhEb88fBkE7wsOIJ1ms1lrgmGA+q/rnaJCWiVV/Adj1Pq6b/xE0LGwsHZKFe+sjUhN0EZrH8/RwXnZFYFwh3r0kjQI5tKgMhHzRKA/uZty72+vA0x2BNA9a+Fzs6RidpqhACEuiKVHCcUSDOIn+mNJZod7pFA3x3CY4OD13CKICMAtkDDp2emtHQweG5Nl70E4bexMH7XmlIIffcRa/Qrs3aJyW+wNwbOAjGWnKRrj5SHK3nq4AdRAg03CcdNsjFoNf80T0kJDSHR1AR83FY4r8VvQpV/+vqylcrzjrMKprPuz8mpkcrOmnTFj1z4ojko5VEBwIDEnCVpsAGw98+FK4a740j9MtTYr+N5iz+dgh0GYQ9DAPNvIUAkDphPvzgJKRnIQZPQenu6CbgzO71+E4zOwuVMH+m0I/8tUbWsUq/OSQNekFVnT09GwwUCqK2AAh1+ghB1EwxXRFsF6TT5KGdUuDsFZS8TcF5ZAkvg==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
