---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgCVnfpEER8WmcjAVAkCLEnhtUn3stUPo2+B33hzqugshp0vkjMPm8B3S91yGMGbEH274NL1E1emN4mySl31QRsI4mvswiacAQOnwK7grbbG2XFDw1lGSM1xGBkx+HUQ7/czdtyDwHSjmoRcol8FN/xWbHz4FJwPRvXYdidb4uxF2JLU7aufvhsx1c+Z0Ub/KfQowHKtdaNQ+QDsYQHgDVcJH7U86rKm8bVrbKb+vgpxm43F+WusJA696vAzcur+2vzsGJgNHh2GD+vLcOlsIDxoF4xXQt3XAEQUc8UdS0F9imQoO1Vqk14MiGjsrZOI2DNEKlHd7UABanyo9xiHcHhKdvPVW8cuWxRolMkeVTuA2Mr6ryD/qGlL2PApLRPdj91/v7GAlOIhX1RYEDDRlueUmZJL/mctRbAJQO2d+cQGvnyS9VhL7q7uv6bnu49yEnKrgP3g3rTOyqk2YSQYz7VNHbZEYo9VPGF1xTHuI+Qwx6y9b8FeXDYcws/59veStesbspomAFWm23iTiTA70uko/MNv7+gecZsO9ZztJQQy1jq4wxXMBbBdevDzMeHQwvOr5bMW2YfYtQgRGQr9+ZMResKrQ88swEkGu2JazC1AlA16HxTCBrIrD+xDxyR0WNwa/mRkzbL//2UyVSWomEzG9UD/CpdXrwB8SiYuh/uEoi1HIru68rZ1ZaEIEu3UtXXznpbVTz9qQ+XZkQ4llCBXBPEOuL7dFr8Xubmq9dzZK/7OTUmKLi22LS5iUZaF92NBmqAZmr31zzmSwY99DL+F+jZymCraJRk7HJwSO2gZqo3hA/vyVHVOhtLgZRU=
    username: AgA+u3eVRudbXxasldRqSjqk1xzWl3Np+OnzBrQQZqjwkw3bmNzMETZIW5K9PoLpvvJydgxclbeiT8fjisBqpQpnvjI/3c3PX+yowBbcDj/v/lBZwdezcSSEzDI7JcbmbCPC6yj9njOzdO+aRlC4CJ6belm7S4aBAcd6La811mya3MyXAetFgAfEJfcjodlD21O+Y/jTk7fqiPSwFlkkSSpvk2aHGPLXtNx+MvebRvmxYHIu53n29s5EyAh321YJ4b8fEYp7hEcdkeaQJCzodCxCnUQFbpUzXALG/wHooeqcfalbhL2aKu+91xqdxNgX7/sHkzJFB9znpvOCcwegS8ckgno9VjuhvuZZFAHIPeDB0gjuUVS+A9vExT4HbL+qrqxNaIrRYY07MryC3W29sPWbWJNOFQlRvFFY78r6dHt//0jnfCx6KRtJ6Nc3hWdycsZg1l+sS7NwDL4XgWtfu5v+kzgE6QNSkcm34wgyOrzKQiL0x9NPiTaSvHZnfAsdjw1vfK9GhyEt2Cvs+kJr0BvVUFz/7mfjkGjkzAE3XIcyB16wBU3UTCHtZGtZQa+iIFv7XYwFpqPKa71hsu86luqbPBwlJ21uuSqZQ/KYuTprCbylL/jCTxqcNJTN5tI7YsRuiyAZ14c3KAsx8NW/OA4YzuCLWoO51v2mP7iuY/qfz4uNh2048ja7kIyOxsulXiSJbdO90A==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
