---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-api-key
  namespace: flux-system
spec:
  encryptedData:
    password: AgAe6Eraw+8dcehGu6ag6o/xANnf+OmH5AUOzv0/LdmErTnv8UixNLabx0qJQl5m50OjXslRYkYSqglOEuS9GKBGGNvPffd4MA4iCvWDeu++9fupwzlVgh63sAF9xc5yLRprsAnqPntxSRqrsbo4PjgiyKCMIMyzId0uLbLazoqM4+NKCalxgM1dE4GD9x/DqbnErL3qmZVTv7jBnRwSITXVQRyveacQmw3le9cXf+0KJZvDgZBIqIU6ukpYxurHXKY38xYgKct3tqk2qrljgxgB6aZrrF+wJ7hObThTeo+nLpUPX08xAa8Tb/95IYp+TjMuRs591kNgDbfZssdWxVUPnTFwj/Egpp2IXr1RyOtkrTh1eXXv77IJ635DyNrBdkWCJU71WzMpqV+KqXt9KI9/+ZNj/kT08ZyopMOmQvTZk0cL4t1L+avk3as9eP7fHEhzLzDRsV0lG2WbmNmmDuRl8l6WOkzmo76Ak14NX8SXu2oDw+ZVHIRzL+qEuVtZNn0FJyr76JPHa/Je3u3di3lo9nJXlveiZ0CaQUDqK0/7991OCGqSyUFEV31ZMvYoES9XPDr3DtyAMydj9WTsT28ISqoGOrEFRR+3Wu2LFfmRaZUAFFzW+y6hRTfd8Wk3kQdEFMagqbsiP1BKJT6DdMTQumZy7l2nC9FQJsV7Q2xIvvcRrj+0p/QrQ6+C372Tl2E6b5wj8YVGtMnrk6IaAGF1zcnwekEUsUbLUi6SkRMti0o58QVOyCnJIR/DtfPNg7QrCgA/f9IjT5pIPvaE6z3Gg9RSfIajSC55I7cI8d31cSJSEU26+7gaXAHWfJU=
    username: AgCDDdDbxx7G6/QJKZMrQarBJkrG9tCRtiCgQPinkRX40wDVT+a21uxd1fq0dVNqtXM8lkfZip/dWUoAOvTzgZ2CXV716fSnOlYlpsn42519U0zWg5CEn68tX0TogHk28VH4gl7yahDnr5YzdqF1giXtLp0qPBjmfgWkuFqeiX032p04oA+6gqnzvg2PjpUz50IE8siq2D7J83baEpwby6IfNaicWYqcyCfmqKUfL5Mw+V3GAvPwASN3LLuAfgSlrUd5HNMDBN/mtGwYZy3rTr9qc6jdvOpdKQFB8O7cHX2FXTLJFd7S0M2iduDGspcfqqA8U3D6UTcs3BESiGOCItQdH+22tEmDhHljtTDm3pfZwSrOl9za/8+9MCDUIHBCGVSYBYwarXgNo9Some4tjggwEg/owIyU/0uvs6SXu/+JjOwBjPAKRvu/9wdCuac1St+mejHnNbs9DBdG0xdGgU09rzRqvefOvTUfFK0y7s5PK7H7NPRD0sXBviwFOr78PKs/En1dcJYcd7S5VeMq2XPAb/2gJakvh1BbhVLwFPKaVq6B4b4Y1MvKG+obgsRVvDzT1A8ckq9E+/GFEU9MuXvzLCcxvvw5G5WYXsDHqIyO9Y7QA4exT7mKaDEW5WTfUPO3a4+DIofyYQtOoTAuAScXyc7cY0EcJ2Yw7ASU5KTHdgZxY08/fzkSZeGEBx11L72/i9jnBQ==
  template:
    metadata:
      creationTimestamp: null
      name: github-api-key
      namespace: flux-system
    type: Opaque
