apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 10s
  url: "https://github.com/yama6a/k8s-full-native.git"
  ref:
    branch: issue-27-rook-ceph
  secretRef:
    name: github-api-key
