apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  url: https://fluxcd-community.github.io/helm-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: flux2
      version: {{ .Values.versions.fluxcd }}
      sourceRef:
        kind: HelmRepository
        name: fluxcd
  values:
    clusterDomain: cluster.local

    policies:
      create: true

    rbac:
      create: true
      createAggregation: true # -- Grant the Kubernetes view, edit and admin roles access to Flux custom resources
      roleRef:
        name: cluster-admin

    logLevel: info
    watchAllNamespaces: true

    imagePullSecrets: [ ]
    extraObjects: [ ]

    cli:
      image: ghcr.io/fluxcd/flux-cli
      tag: {{ .Values.versions.cli }}


    ## CONTROLLERS
    helmController:
      create: true
      image: ghcr.io/fluxcd/helm-controller
      tag: {{ .Values.versions.helm_controller }}
      container:
        additionalArgs:
          - "--log-level=debug"
      resources: &resources
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 64Mi

    sourceController:
      create: true
      image: ghcr.io/fluxcd/source-controller
      tag: {{ .Values.versions.source_controller }}
      resources: *resources

    imageAutomationController:
      create: false

    imageReflectionController:
      create: false

    kustomizeController:
      create: false

    notificationController:
      create: false

