apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  url: https://charts.fluxcd.io
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  releaseName: fluxcd
  chart:
    spec:
      chart: flux2
      version: {{ .Values.versions.fluxcd }}
      sourceRef:
        kind: HelmRepository
        name: fluxcd
  interval: 1m
  dependsOn:
    - name: fluxcd-parent
      namespace: flux-system
  values:
    clusterDomain: cluster.local

    policies:
      create: true

    rbac:
      create: true
      createAggregation: true # -- Grant the Kubernetes view, edit and admin roles access to Flux custom resources
      roleRef:
        name: cluster-admin

    logLevel: info
    watchAllNamespaces: true

    imagePullSecrets: [ ]
    extraObjects: [ ]
    # Example usage from https://fluxcd.io/docs/components/source/buckets/#static-authentication
    # - apiVersion: v1
    #   kind: Secret
    #   metadata:
    #     name: minio-credentials
    #     namespace: default
    #   type: Opaque
    #   data:
    #     accesskey: <BASE64>
    #     secretkey: <BASE64>

    # Enables podMonitor creation for the Prometheus Operator
    prometheus:
      podMonitor:
        # -- Enables podMonitor endpoint
        create: true
        podMetricsEndpoints:
          - port: http-prom
            relabelings:
              # https://github.com/prometheus-operator/prometheus-operator/issues/4816
              - sourceLabels: [ __meta_kubernetes_pod_phase ]
                action: keep
                regex: Running

    cli:
      image: ghcr.io/fluxcd/flux-cli
      tag: {{ .Values.versions.cli }}


    ## CONTROLLERS
    helmController:
      create: true
      image: ghcr.io/fluxcd/helm-controller
      tag: {{ .Values.versions.helm_controller }}
      resources: &resources
        limits:
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 64Mi

    imageAutomationController:
      create: true
      image: ghcr.io/fluxcd/image-automation-controller
      tag: {{ .Values.versions.image_automation_controller }}
      resources: *resources

    imageReflectionController:
      create: true
      image: ghcr.io/fluxcd/image-reflector-controller
      tag: {{ .Values.versions.image_reflection_controller }}
      resources: *resources

    kustomizeController:
      create: true
      image: ghcr.io/fluxcd/kustomize-controller
      tag: {{ .Values.versions.kustomize_controller }}
      resources: *resources

    notificationController:
      create: true
      image: ghcr.io/fluxcd/notification-controller
      tag: {{ .Values.versions.notification_controller }}
      resources: *resources

    sourceController:
      create: true
      image: ghcr.io/fluxcd/source-controller
      tag: {{ .Values.versions.source_controller }}
      resources: *resources

