apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  url: https://fluxcd-community.github.io/helm-charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluxcd
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: flux2
      version: {{ .Values.chartVersion }}
      sourceRef:
        kind: HelmRepository
        name: fluxcd
  values:
    clusterDomain: cluster.local

    policies:
      create: true

    rbac:
      create: true
      createAggregation: true # -- Grant the Kubernetes view, edit and admin roles access to Flux custom resources
      roleRef:
        name: cluster-admin

    logLevel: info
    watchAllNamespaces: true


    ## CONTROLLERS
    # helmController:
    #   container:
    #     additionalArgs:
    #       - "--log-level=debug"

    imageAutomationController:
      create: false

    imageReflectionController:
      create: false

    notificationController:
      create: false

