apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apps-root
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  driftDetection:
    mode: enabled
  dependsOn:
    - name: linkerd-control-plane
      namespace: sys-linkerd
    - name: nginx-parent
      namespace: sys-nginx
  chart:
    spec:
      chart: ./k8s/apps-root
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: {{ .Values.env }}
