apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: platform-root
  namespace: flux-system
spec:
  interval: 10s
  maxHistory: 1
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  driftDetection:
    mode: enabled
  dependsOn:
    - name: root
      namespace: flux-system
  chart:
    spec:
      chart: ./k8s/platform-root
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: flux-system
  values:
    env: {{ .Values.env }}
