apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: platform
  namespace: sys-fluxcd
spec:
  interval: 1m
  dependsOn:
    - name: root
      namespace: sys-fluxcd
  chart:
    spec:
      chart: ./k8s/platform-root
      sourceRef:
        kind: GitRepository
        name: my-cluster
        namespace: sys-fluxcd
  values:
    env: {{ .Values.env }}
    {{- if eq .Values.env "prod" }}
    foo: bar
    {{- else if eq .Values.env "stage" }}
    foo: baz
    {{- else }}
    {{- fail "The env value must be either 'prod' or 'stage'" }}
    {{- end }}
