---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgCqX4+veKmdJvfFd3OJYmyiio+JpBQPQ/uEIlTEVLKIR8odh7i2j5shp+S6y/+pL6q+dbDH4gMXapnZHH0Nh5Up6sDidQAv2YLzVifjASwYku6gxfYHLYR56QTsQwDBzd3qTsDwl2v2y8nU904ZzO6S8nLfspr4XWiuGXouITN7N+GIGPPpGpGwV178/BbO3QGkmfGantEGBgwTO0AYK9e0ETsn/woaoXvMZ8QgbXIuL2T19+4Fru+9dCGgHk0MFGK2coEl8nx8IvNiZ4Y8pON9S0qJ+oDmtAXAZ3DouQ7x6qVL53TJws6pj7CgFSyzlptXV0SjrszROdVQ3kLQgWKpoIjtnt+MbqEMHefmKCr/bZ0ZbfmKSssMrNcJkdW3tmMHJmQGblqrxlK/XH0yH2Tpw++k0yZnc1jm+qmo9a7VcSjYpgU+tRnOmd+Xko2xnBMgRmZNLmsNPV+23FgufHxkcVD1e+0q46+umutHxBmpAsmLXBSlZ+JyAEYycKKKeCFxRvBcieQPAMIy4lqwt5ZwFj4B00Uc6slzCD9bqEJUxYafnnX0poy1PRTcqQTKAj+sOckTULOpDnvg7V1cfc0pwb9BtiNbHU0G6e3F4E/v1hWpVjx/62mh16NqL0i3GrvhE2SEnLOs1uCTnAONxdpslAhEQEOHRnA0hs0SS4U36qBBTgKgQJC5N86M5UGQgt3xkGL/wqo8U3Rx4pLEDAssrdfuXsUwM/BXAixFrcQRRt1yWH708Nt1J64tNaHnWg+QhnECZjWVTlt/SN0=
    username: AgAXqKqIDO4lT1JYaUNpgx/KjAgcUixN44rBhTtLL+L5QEvFKj3n7zwGvaPP/xrBaBWmbzwfZZag2sDayElrwqfnJFfsqdJMTsy5G2TF7nYgLNtBU/QP7VWapRNn1mm9plUTuDX8XhaiFjuFecxjINauEk4MHyeYKVySWCLTBCOwP4mpw0iOGkTCDJ34xqtjVAjzx1rXuf35XCE6fGgNpWXIdKcy3/TpJ1BLIj96gnRjmZDCwBVc6EtKUKl/mscPOlAJOaA32YfJiJJLTC4f/cM/xhA3IMiLOe0jb1rEbd7apBsDaorcAtlsdDFhzDfi+ZYnZhiVVK8pkTWHDqgdHzYFxNTlhgwhvdWFpolTMXVzpERkxw4OKc20LG5T2eEQ16FDryItNFsAc2Bz3TBBTaIk354sXcSf6/WMKcPn1pyXX4EHId91nBr/GfeFHKnM17VBXsA3+jkxwX59Oxqa5RaN8Y8e2VYIXYhDWz4eVQ08qA8MMxk3vlvQ/mvkupSltuZVxI+Fj4bvnzxR/NBYkE9n+a2SKyPTqbqiw7042RozDXE4FxQCCscH3Yr1qhK1vI5rxaw+dlzwndCeMjItqla+mPZVtooB/vviC4b/gSZPXyJhk/E16LelczkDD86viEd0N8QAqbce2V2TmjQPaojSyEgPxctRRpkkd7g/TxpV/GMMLlI1SBkF5isU9Qjlx3vttVDwPQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
