---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgA1pY4AaImU43D5Yh42vM9FQ7rB7vQUCGKNhmPnM+oBVR3PnMya8eRVOa2ILKHrz8BFg2jaloxjFWJBumlf77u3wo0xQtfNgZ6Ko4BIz/+9SI9+gnxSunYx/wuUP4dscm23M7r+1jcrWE1oFUh741i2hRZa9DoVvhllSEKmM60nkaMvqxr/RDTTpd6lkOknZWWrUQjERGf96sshRDu/Yayq4TS7G5ZhKtq6HHh07E8X5c3ZTFp7Vn8mFiqRhkFlrFuhslNv9AvFzngw9EFcmrZjIq8AADXCUVciM/kh0BOUK6Xo88504noyJculrl1q3ZNDIV4cbd91sP1nLmPHx4mjb2z+h7tHwX1sPzQ8BfapQI+99Cbl+tYvqyYCcVF3p+ba1ckfCXB0sX8EhkPfByvaWVwB68P1OgO/e7vUEVFeUF0fcdRKNCBA9pC9QNq5GXWls79lu2l5LbsccBvAaCX5yeDT+STZ1FXGbhYLZRXiKWru1/3se2EXtNYaWZouDsWrFgD8FlkFvk+NA2GOeNww+Gfd7j0+AdUcs4LHMjq6dw2Iex11L0U2s1jgyXh9I0L4GAwxjfAEDuxac/QXz2luaWE8yDk++xS/s7XsNwfVjWx7eqj1mhUCFqlpSzp6CaTmULa9DsZH1EOVaDA3KefotbBoK3Ut3cFzhgIc+94BdcHAnwAEWrF+5XzXSyFINa0PHwObimFeHOyEpjBHE5o1iGv8GBqgMofCv4PPGTjgABHL303+sEyxz+Dw7qwVzsarc6I7fCSHosJV4pU=
    username: AgBx2DO04HyPBgKHgHIJ301OP1iO4Q+VVVezRgji+/9UVuy6kc+5Sz/MJouwPD0NloUoBPpmIbZw8JLlnr+tK0n9v+FNoDd9gxY60e091sjL76++/HOyG0e1+IzLBt5Gtq4SOP3+iXdD/+nlQ3YRDmP1XtDz8iO7KSysBVMOUyNy1+9qjSZwB3Te4O8cB2taY1VlBlHxk9HoVfHbURmn3iH8lyscbOwJmmhVtSP8pZ8zH3Wx+xIdgtDj4kXDlpuUH3FNB07gQuk0Nrav82euXahElCJ/gbV7TnMGWJY6b6HtejVcg/0xlwEdlvj7qXZuyhqrNtHAQ3D2Plsht1I9kAwJOh0ulTqPWIjGDTS/yzZt5pAPikysq8sinLMpTPqW24uDlUiwZYjj6ErvpuFQN6YVeh8CygzGAfhm3joue+N6dOW/lQ4guzCnNNhtsrNrVQB5wraesmBn4ZpP9HqPtbKzidNUmB+0MgL+m/sG9cYLimmULSGuL0ahPDjzC95salX5jOjuMF2aCHbGjMdn/GrljFNhjd2jfg2BmqtorUG7Qp6dq4/TEJKX2b+3wisD2BF9DGhcLnoZ3ktXiETe41NNULYzGldnw4Fbq2qTMTG02563Rc2pGoeFNsz4OdWrE9SkMA+OgLMu81Rigl5iikB+X80kH+zuHoiVk9Yp1hn64QfUyRjEAZAeU8JSjOfnKn/ehhthVA==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
