---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgCB8ni4VvTgL1p/uszHO74LlKNULkEWmJo3wl9hLaBYuWaZjAU1ybvXjPu9RTBYJgL+VNXfpNgVLqpu14P2Rfnmho03Uvgg8xHz4T9h4iauOXOVDlisON01ObjsqoY5WNorTFXmvBdpbVuexHkLTGuF1v3sQT82AlOkg0GF6LnrTK2wG7plmwRXLX7I3P78yfOZBeOA88rhpMF7QUdJ04gETXjudkAG+jrGqsQi+z59d/ZLD8XiMw2ckd0egnQODlolM/CmTW+8q0IJ030QdWU6EwDvbrVXEaMovCbmtzaksR5e+6eiOjZnmXY5vgbuuIQVLZUHsFb76S0WS0jW0MYdnJohNGDL2j85pHpU4eFCg9nmU/j1uBBaMvBulJ4zIbSMmUbZIzbNTXAdgVf/EL8b7FNhhau5xhv+o3YLsTckPhnNSe6kXL2WStM3Xr74MHeDlFO+2F82zLTYKZ0upcRokMRNTTGqCXV6W40wZpS9NR5HfkZunVtxjsFxOoXDuRZAx0JO2HoLvL5fCoJVmNGol6pjzULsOeNm8uWp7THDPzIviXO7LVeG9xSuSAFpOtkHVXgg0jADN45ujIpSgA4DxOiABBjVNgnVIv/JeBeu+0f8ZixQtYfUjAM+jmegZoLlzGJI6pvxjdH9UxzJN6kxCmGdE+YIHCYQ8PTC85a+dUejLEyVJsNPTl1z8EpzCZ8pHb8b4AAlnkxpiBNqGkx5YJcaxHcFY7Che5JDJJwJ7Q6tKCTWA6Fy+/EpcfevhWU2q18bQVcZWdd4JfY=
    username: AgAUAtCV7xkoJPitR23cSnO6N74wejdDmwoCs15rMxvPpXKdX2HhemyTOgzDOjtPhXgJkCDN2lUUn/uOw3sRhC3OYN5x/Bpf30YAOWbTSfcbBm9mc+rKLCBkxw7d/YbkEUgbJAYUkpku05vGL7heWdMtfLlQtK4kJjlJ45ngfK737JZo1mxe911fKmZZEOY1GdNPNvOH6jngsWEvcB+kk9rgaNpTkXtycQone8PsKOMuDtCAdWdsIXlUV5BASDxmQFVPf+MotpWD2UhK2NNaQmqY/OrYf8twABmgEi5ChCoLGD1uHDmjjl8pCLTZDHFQEj/Azm6jrnsq3yBhWfhn5Sk5ut1k16Luj00XaSDequKnR9CQEMa/nultXVXE2y2DB6Fjofusf2AmIxOHgZ0wL8JAFPnaGkf8sgZBhApUdVZasonCdpY7zca4wCVOGkVgG6Wup3QjrsAt4V3v3KhC4fzojcV0yJ2+kdnZjwbomQ1cNfdZDNyCTNv7xU9toNNXIJMgO2slKXKa+Pfus+LbdHaYEIRfHAMTPCPMr4RRFwcxzj2SUxoPhuiO+xRMt3YE3hryHHa4mBUvCBQRcIBxy8H2HR4YocH7HxDkuFRLSBCzgT5ujHtV/bXAyvGk8Fsx2A0hMmq1go2+2tHm/zSY4JKa4p1i+MM20MR8oYHH8hE0KT1X8QmQ2+XF7DrALOVrmt+WfD+JtA==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
