---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgDH6PIic7ko06P/5ZPnduR2bSfOc8saOBjYXngmgRZM003qLYvzOJDKITtKMP63jB2xecS+tYNVzJhgjSfHMW08LNQX0u/rN6DwzbJfvGoQqxOq28ZEkWrZtKfNj8zzcuTJR1gehKVyQdNv5dk63lxegR64ug2UPZK23/KEEIsOQ6Lb7ZR4U1/rF9nEeLnKZkTDZHcycerro/wqeRoCqgkQixhcckJzrOFh1zesSTe6wKDnjerMuPFE1HHnVCLD0NzKQIcqRCrNqXbHuQkkcYOBiHWejqTKSeCHjoIUQ92pbQaEOsaZwkyKXFgodpupYyF7uf6/frQ8WqkrR0VEQKn0gWX7GWlsU2bH+iWwWKBSLRDZNYP2Ndpg7CJFRzPprs8FhzdWOb5h/wO9ZZqtAmhpSCm2xq88Q6Ywk/NXAnL1R9vZi3CxHZkocAHVTg7JgNzdKlHeBGDuFpBNC/GWRzRxUqZYj61atGKSJ7661KN3p8osqiEwVVx876MQ+mujb/biGvDDLpvSaCThrkRSdrgupElpuSMwJd3XnhWOPL6AHJpqhT4Ox76Epp84Z6uzctgU7cTwx4ywB1tRi3+O0p8AOhiCe2nSSPxrop3rzIESkWyx1wB6yI991NaSh71EAGY1K36QWtFZ6zBpW1T0TCMuQluMplUos+vPpr7ppMdWzb+MojoRbkn2N4UhhJ/wXW0nHHWn2ioJCmNEiyjDhyg0wJSIrr6tuJUAaVyp+KALnxvGKfTcoY+KEVdV/8F4CIFP7rzyosviul7jjuE=
    username: AgCjkRMv6oOn5sctTAGSJcDVo3yWmTlIQZD5xgkMEhKdfu5gi5hhn+c+UXZyK0og9hC3JnGj12fEa1V8Fn5x1tnEAV67IWpyGP0EFvgikNqQvA5YO4QdVtcJCySHalnwUTZm2mD5oRZyNhY3xRJsrX94u/l6lqPunpeO55n6n04o5BfMPoje7urQrfGFRcgGoS/anI/oAMongn5kovCIjuzRXSucKxWPzOtH4LfkbGrLak+XeMA8j++XwNc/lALz1s70HTNdA08cW1LMh9rNmh1BnlZNkOhrJQN4+tldS1bjQzGXaYAP4TECNmhjqwdeHDu9SHWVx9YCxSMHipvVANpmXt66mR9dtFOOInJoGO2IhOAa5teeTNdsHkkkuiZGb4EX15cqa+7ZvvwFlwCGfipcfIUcp6pkuY4tm+HcCANC5AT9OcQ37fqBWoElZvz1iX4Yp8+p6DlZFkn5+qIDkKIJu09mgF5qI3UAakx1iQKrmZRVZxffRvvGWZn+iH7Q10jDbbVtXrg8prHH7IrAFQZbTov3pPenDfcS2Xb/7/qL2FLuWBXqlMMPFBWU9Jjy5W+kGfWWv7qwwPrphi4K9k+OAQCzEf04qTPSdJEFZetX6Tl6CE14Ng4F1qJzk8e53MZ4a7PwSRc6SSeBF3a/NQndawJffVtBjwMOdl1tjb5Hj5vzI5xgTUncEK0wi1v6OrLj+p/WoQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
