---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgCdweJ7d4KNJaLs8ZVmo4qfYCTTN7y/WxL+bYm2ZTJ12Jx1vNoUgdsHpC+FPYytqG0X/ap0UIEuhefyFeOn6PdY3zgtPzEczjtoGT81ZkcpgtFsonUN1xy9yVoHGnTeutInZ0s5b4FSohVy7Lv/9UFdBmeOvyoqViIQYtzLvS7amaMOMzfC4Zyc/7TgApgKLTsljQ1mmKmMGgLigtM/f65l6YCBHV/8vLg0xnY6Amq1Q+efxggnp/4wZfJ2ZgXwabYE+mYmpiYpr4PcUNwn87L8HjnblAUe9vwmw3BGud05bx5sExx1bZjRFyW7W0yqpyLwQ4oDFCkUQ64JINJ2DzArch97IsrWBcujvHzCvdimJEzN4BrNBgpsxx13jOLtVKy+NcJ6OzpPOkmqJi9b+H8Q6rkevttki2KgI7EI8NjxPON70x3vw503se5NezxhupuY4QCvnaPK6ADKGF1ygTvEyWcrXRD+qY+j5aQ6ZA2T2gCSDrIZDT/nsRy+ut+GqtxJXSSnxDIg8N90xz+E/IawBY5dl7aNWPVgfljqeROf7+om9ILWJqnwKwO3nieB+HmpxkmoimK3/I8ShVJRvmXN0wgcfz+RWyckCTZN3YMbRUvMWkU4zex4lMxJcjs62kYM7Gih0Lvwm4It5plAy19VTogwIWLj27CjNtXixrqSmBf7vSMcgxMA5cNKI2vOmIOe+RyoEUrTZqnOkFTf5CbT9HdXGCcvuYFQVc4BJ0tLXe8h22LSo+XnSVzp6ZqX7dU4uKaCtMV84mBYK4c=
    username: AgCXA7x/nuewt9tLb+boVodVE6xWWuXTTS9bgi7Jw05bnzQprQ3Wj8eF6KFeLAUXUcHtCF4gHhF1jh6w+tFwHWcfsCqckh0WnSRWhVF9Cg5iFYc6zbMbTrq+lzK9RLMEs4sas1CZuwCgb1RcTC6ILRrt4nCgcMy+nMLdBXQPDPr/SOmrxL8L86+FMHc3XlJLCWw1s/u/Oa/PshjUVpzaQz5SWUfp25tjdIrItgBVBOJSIbVdsNO6pkz9GH7QDNg7yPwexZuXuX96Ma9u+FRz1P6HSgwdCIlRfVM48cWflXxaegc6PQB1z3RjmqOnSs/XqlOjttXIAv0C93Lm+1mZ61EGV6/K4TVRq4qV135/KnoxvKv/3gWOSLRdU22PntW8l441EHc6MLmPd/w6VqjodjafozzP7rj4pBaQT9Pw17LONkrK6RLRkriSxWMGu79d07+ZnVMTre5pMEG8CUnxzzYMwe3olUwxt7u1ucax5pwC7fWPmmtk+kBD68+lCs+0Kj6K4zLo5oAu9lCAiBSbOqCZuXPfReLdKYKGDG9VJWftfnwYNEL7iLor/0NITmCfzt1IxxDtQRTAeaLkwdEBsVklOn8qKn1qJ7HHgy4b1BWwL8uQpiZReShOdS5j+SQlsadJsSDmOR87hNMK6xD6tZx+0R7XTR7FBccPFXZZTFZE6SNpNlNjfLfE8knHKLOTBB/RlzXr4w==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
