---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgByNVT1oFXMX2a+0Fy4GT9bASqFXKZY4zs6F5RI68q8bDfm8B0FW91rG4U94dmnl1t0Ve7KhJpmtMnV5ALJH+2kyjDIwJaeCCvJ1dl6PvDu7cByzrJf610VxdQpryE10j+likXieBpcZtCdOVu3WhaZTPOA2fuWLYMhugkK4zFdHpKjHP+xP8JI1OLiJd+k/CNPGQ3iahlRbANvglJw+95fqqdRVI6eTxp0hnPGQ5v/LcCxWwNR7JSIkEq+ykI7l7UHvSQpRPmIm9Sipm+9PTCxVJ9Pp/M+RV/CmlBmOvxzOv/V+/KuD6tg/qs+JxeWYM7tKPqJMxvxF1bXA1P+bzV0AqEIxAK/oKe4KHRZ0Simpo11xqk8QMQlg/3zhoJvVRYTCa2U2uUN2yLTcvr5Kcxjj2aPFRrzgFw2YOhZ7YCZSKouDqwI2730N3S5fZG6dWNY65fi5HxN0lOIy7URUIXSJS4kDCsevZ3mVnDgpVKoysuMwPxKa2Tksr3PYxKTK6/1tEp82NBfsPly1qlpa5I9mIYiMhHRD0lFuweGVGFY7rcueHgIqMPfA9MNrtzYMocjJWjDh5PcyopZ8fqW0bvwhwd0/rK3b1aNtCzj1aDTT6FNcYky0x5wepkPODDwvlzRIsZ5ZYfqJfJMd9dY82xOYXzeTUVlccdBfedcPpPK195oJIDBMRyCYSgakhSM0e5R6LEeFD2WSvArAC5fVwucB7Zu0ZPOz/zcP5vuH6WYRhlkapwhcwrftkheDP0U6QhHOwJPb6jyBvKVgv4=
    username: AgA4cOJXMbcPG0fcGtZ7kyWmUQo+W4tiagr8YuuzzIpkbiaCJXLmHY49Orj7SFBpED50P9y6shB1N62dflMdLUOwH43DRtzlhSISdQuPYfV26ZQO3O73uJep+V+KT7cB4DDfd0g9eXqK8H4dT3Vg1zI3rDtjhvO5Wor6KuHyl57yGuSFNP8ikKe6iziabh4y4ateSbNarz4Uatar1b/VVLZ0+zxLMeyNhdTXd9kWoPP2U/IF059uuBsfmcnS2GLYOTEj9fLy2aYhv022YF53P3S1E0tklJBNUis99bkcTuhY05ukngpFdpKVv1aifIUZGjezaXENrTJFS/KkPFIHOui0hH8lRK02kOLdmYXPygYYF+Udj9pLLAKXaH4nZklAzq+XZeRdLvfSnZYZgCrM9k0FwfnvYcC5X8U0MePqx/aHv65pvmP+5MKwHTPKlBe6GG1iw8b6RcPFiojdshFtX0Nz0lYui6kt6MzcKuaTErwet6zYVNnQOa9K1eCLwQyWpUB5YXqJEOsTQleUef0H8k0IFZ+O23yiR/4KMJayp+x7V1++AxppM1xtLiSQJPq4m4Voh4x5H3NbWGsZrd54HdeL3qp08/o8ZZuruvGNGJLvAgkzB1l6ngFIc4/gPfG1xPbSn+ADi1DkBNN5aEWBl6H88vL2rDJFEBnp2gQdpg3WNlcbrBputM3g5q2r0QEyEsxvu3JZrQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
