---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgC56eNpurV7M034KgD10NJMuQNFjMNUo5kCBBQ1ko7HTiECL7gjay7JHivXhMQt/XI13Mtdf5TwibrqT6KGFE46SihQOtwKepsSXHKmn+IeHZXl5NQA0eVT6SaBcnZMp0fCUBw/kusVuse/4OsnEsqr3jcKBeCxKXNX1QlE98mN8m85Q0KwB6FFocSToTLYynD0opBqoTjix4UqVHn8TL7U5FZM/Qtahb/LyOPw+kjXZzqLj781ew9l4PwpEB0U6y4R8+6AB8ptk96NvTUTnrmtZUV3tIbiHLqp6fYV/hGcr1zm3SJ2XkJc8NCfVaGBGYkHbRGrUzgDdMQChofSPrPHIcBVwWn4wk+WQU8xkhsExHHrS+lSUSiOgDjXonXW6QXIrVhrL4RyqKzULTXIEFNCXM6s4J3zD9k7USWxlAMB128//1EwHbWaK26M0OsYExbMPbWiRBFmkO1KhUfJqMl7jQSfLFdm3wn/v62/I9UtYaVkcYeRy8EqoRl/bjA+umAU0o+s0OqEytwoSqtSwY2Zlc4yRvau4VQZYohJPN4OPK0mzmbv2SptwqAcYJvsrdR1tDoF+qj7zHjPq+zGAU5YzURBss//ImPOZXXdSpQIHT3fmhGiPEB+hshE8tNwHyZeHrjkXsRFlN+sBshlRB+OZDXMw0BC8NXMzh+T1Sp8quJXtHFkMTTl4ZQTik3oeMZnVZFB0EP6hxDphpgQbWQ7KKMhKASKS02xc0MWEr4Q5wOWRO6of+KSs5bBZJn1ZchbyxpofM9qz0YGS/M=
    username: AgC5QZvWVIAzD2t9aBahzB+yEOTb8uA77nzGZ9p+Q+Aa8Bw7oHWbgQOIsMsd2CN0hKIPrw/PHDrdwKAa76h2C+l1ZP6vFOsX8idnkULPJJIMy/s9ZsbrWhDtj8D3krm5Y0mF6PKWD5J8xRfmgQgVZ/UhS0AfXIGlNuW2epHDDoCLWuxJM+QWsasmmDtQlnChAAN8/S8y3VcBEuGB6Wi6wG2dPaWwN5HlPaQmHVDDxz4XJCSENUtgKbLcT9ROP43NA6FSWHklqPgfEAc7AuEWsvTzJ4CNx+Oxv0SnrV7UGcMAN7eIP1KrNOpTNKh8ycOm45PclLo2dEq2aYEGoVoVcUBHTDVftKi/jdeymG1AYV2FpzAZdD9+aNTkj7cgq82r8p9of6BZlTg7nzTu+59n+9l+ReionkzB0y4D3n/B8GsyXxAmLfnRTukDXlQTsXRp+wMwc+l8DGaLMpwvy3VsBOK8M8KZ0Kc1CTyCqujsr+qZsSmbkIY7bsUTtA0t3CM77sX8pVAyeEhThjSbYj7aRJqONZhYJYZPP1rmFGMRzL6iQqq136EkIzkNx6e1PVwa08prqrvXlQSzeA0FTxigPgzKIVqiJ9D4WqWvfKdqcsGu6jNxZ76xefUnWRRUnf7Xp1fvFI50ub2velkKVd2YAtqgfkN4u7v0xDJcASmP90s38up7xa/iKzwFjj7Zf5Nabc3/t80JaQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
