---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgCdVswsqdOOnRlaKWICUcZuOujoWQ5OX6dcHP0MZvq2uasdpzAiQLGE2qwVXfpnCz5DX4Aqmf/m92xUHYTi7Q2ZorxnDmT05F8yn3K0uNpE7QiSXwW3Z3V3vchHFaxJO6GsbNbJAbnuRu6d4srb4U9wYEmgyzsLbYR3oI6XSJKmESWRl7lIoAROovd0LD68UTL5NawfFE8+xvPHwIUduj8D7VOSZBWKvKoJKgzDjKc8PwnkjSuluNPLYibunjMuqLC5q0nkZLNkHp9yP5PCPIDP7z7hGKv/TtdA03s6R02NYAoRmi04eW+KpP4qWVZEC+UnGP1rPetXeKWZtH9onnt5YUyBObTQcvSHp6zNZF1jdi9AmBJk54f71dr0lBNAUEpod2HwqO0G+i1H5T0AVFCuOXudd+P7BpB3XXgSHpXOneLtcH8M99Og/j9tS8ratcYb3lD4qavLyUqujXWQ8869xYb74ZSs7T2EwUca2U1mHQt6ekXFPHe7Hek5BXDPGE6218LQsN9eyYYLudvCXQMp2LtXMVFuzihB4HUpC63xOyjLgycVsUznwAsv+whFtPYyrIH7kL7N7t+/XMIVs6yQZHUTu34YUJ+ALWwNFvspyFvjQyQmsm7Wzbls708Ghoty1iUc+jc90ww6GMEfiympn0tRTyeG/62bnUDJpsyzjJ4N+BpNHSK9csK3Stlge2NPw4k5yMEYcybg/ngNvhRbB9msbJf/1uMyfhN+YoS9fFZoPq295uVJpMg0N7gQafZBIMXxK0F7LztLoi8=
    username: AgCIYrETP2lMo9ChJ5sem0cnyUEBNOhIsP+4vKhFajll93RAsap7Ub8ibAeZd12O8zbb7xp/6+3dgJpMU6CCwNO68+QPyaNE91xwmIXNSo1b6xHgtQ/qx2MFW3z92YIYeq1TjvJRn3uBS8vdmz7V5jO0sAYalrGnoDY2AwOSnp2GNN7tk5YiZbIOsofAD5BAzAkLRfSdbGTocmTcFM+5cehzXfaDCQrt8RVCrr23g/wMsO+FhUjgl8HrEXYxwDND8jqZwvTfFS0pP45AskkoAZ6mfYb9x8JQiaxelS1/CRotUJ9YWjnkiEszhhUNJ3gVYlUhhxAI+GY7o1Z+FCb388ow4hJMl3fRKAmBqnmJdVjJJEkb4t1WQSsvZSbukJw/d/Rv+ZF+ekYhVs5UcCM3r6X+BRgjtGxL77ULjR6S5acZRLYEVdtsywhXM+464l5vowTM9Of+yhw6keQzjLHprsghWpifr3T/zxaTcSiFhsF8DXRGIbFN7aoI3aaSHH2oAAzdeHSeu91eNthHbyb3sy6NviNPq5G1mvvd+/KhrHP5U3nAqoE7Ql3RTNE6SDmBG3CsqpQLHbDCWRWBKN3coB6zggGQoxBk7W5i1o/q5gIGht9Say6icc3iFrRI12x0cWoEFSMjFHrRurNxkOp0yp17EUK/ASBDFYFmNbbrVPywllm2HsV3poxrAhTZU1n7+kh4VE4Y6Q==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
