---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: sys-weave
spec:
  encryptedData:
    password: AgACmnU89d9SP5vOp6KFitwZw4QMyCeLr2LEbzAdSZAPt62rBRKZnDAcPzZUD/mSx48qvjDgAoBN/oVzc76ZWpHlpnklR5WtmP3Fxsnn/ofv8yT+uY05VCGBRQN75qIFzl8v8b4UrJSJasF38+9wfI6qtv4VgnCWE57V8G7pFkpU7IBqS88BAvR8gYsiqmAEyjLeZGjPfzgStlwhJLXjsQ2jCE4Vuny6sedkTVtuy0Q2XaOIfDlCw2IBs1K1AN4rrnp4u66PbwAzpFPX+6XakSkR+FbkX9JWwVaO0RLXBTZ8ydb6req+0uvA3j+9ZhwBKgzdLs5g3O+57YVWXTeRtPkujKqM6byupx1159sujp+1LOPtHzeXqh09Abq+oYI9gqQm3w2x5vKQJl9vus8hFvxRRtukYiYGTQDVgNMpmxW915j99yWLr/QApuB0t71R7yRtN4+uDA5z76oAC6wMaG/P5wwudoC9VZhDVJWJmbIxmfe+u91FSQxkuk/IfwvbxDvzJF/HsC18qjGqUYjqi0mmOy03x0ZeEUjpk8oJU7Wm9Xor+/q+H6tPQ2mRneK8ZCFDfkWYgw3jsFABsTZ1mOFMVqn6aT1PAdubzijjjdRmOKazmZaQE6JT0SW/KGk2NcFh/cwyOTNnyHiDw/aoY/jzJNPyQU66Ya6jNF6ihhnsDb1KS/DvBalc7vw4NW5vM1yo+yHRE1bPL0iGl8NuzeKP+1CDAOM/1vfRscHBatOqnFRQpDWNcVtlZWteP9EU1+75sz6lfgIc1uEoClM=
    username: AgBqKPJzPEELY+jtVQ2t1/QaGtarqv75+56hzBs2DIVWvm4tnotEtIyZXSnfa07Zul8bEC8hgyRXdd5UeYiolLO44a6hq572oA65929+2S8vgEoz6zGh3/zb2jtPBdTj/gOLppzGy2YuKLh9UtxuMsZCHRxnc96TD6SESXnjbXHkh8hh8MQAWbb1qmkDj2mlelWk0Jx1N2NpH57NBjbAQZ8DlrjJ4yRX3r+G7iRv1q/EfqVPFeTn0gelAxa+Ed4GK3sA5zEfnlqEzQXqO5dIL3+1QtKhVwa1O7MRS09diQqZbTLZFWu4Grok2Piozjt5zLl3O7+h19pyGYlGqg5f42cf8XeqEGj1Okh2M+gMba3tbSdttkMVIIdxkqYpINhZEbDvtdPNo6GNQJLCWADlr398qvKjWywdtfdmGV+a2Djvd64bMJexEO7908ThswbQbVyW7RNL0XhYnHSHkAG7kA+gnMCcRQq8F0F+pMcnpuaNtE3Zvoaiat+sL+T0U8LuOO3Ls5bs5OaTtDgq2TPKKdHAIDGB/EPYiNd7Gn6eCbiCzC4JpWU7r32NerNwovwWw7bESyTeEpuiwjXfLAp7Ai3WjFveEdCyjnmSm8E8m5AEx8EotEnl4GRKiaa6ngS9G9Vupt6WuulkM+5kXMHNQu42bDPuOnWJ5UU23JnB0VdBrNsFAj70k0+Dd2vxXDS6UIaCQQSCjg==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: sys-weave
    type: Opaque
