defaultVaultConnection:
  enabled: true
  address: "http://vault.sys-vault.svc.cluster.local:8200"

controller:
  replicas: 3

  # Settings related to the vault-secrets-operator container.
  manager:
    image:
      pullPolicy: IfNotPresent
      repository: hashicorp/vault-secrets-operator
      tag: 0.9.0

    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  podSecurityContext:
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false

  # logging
  logging: # Logging configuration for the operator.
    level: info # info, error, debug, debug-extended, trace
    timeEncoding: rfc3339 # epoch, millis, nano, iso8601, rfc3339, rfc3339nano
    stacktraceLevel: panic # info, error, panic

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        # Anti-affinity based on Region
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault-operator
            topologyKey: topology.kubernetes.io/region
        # Anti-affinity based on Zone
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault-operator
            topologyKey: topology.kubernetes.io/zone
        # Anti-affinity based on Node
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault-operator
            topologyKey: kubernetes.io/hostname

  # Extra labels to attach to the deployment. This should be formatted as a YAML object (map)
  extraLabels: { }

  # This value defines additional annotations for the deployment. This should be formatted as a YAML object (map)
  annotations: { }
