name: Validate git-repo.yaml branch
on:
  push:
    paths:
      - 'k8s/platform-charts/01_fluxcd/templates/git-repo.yaml'
  pull_request:
    paths:
      - 'k8s/platform-charts/01_fluxcd/templates/git-repo.yaml'
jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/setup-yq@v4 # GHA version
        with:
          version: '4.*' # yq version
      - run: |
          branch=$(yq eval '.spec.ref.branch' k8s/platform-charts/01_fluxcd/templates/git-repo.yaml)
          if [ "$branch" != "main" ]; then
            echo "Error: .spec.ref.branch is \"$branch\", expected \"main\""
            exit 1
          fi
