name: Validate git-repo.yaml branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          branch=$(yq eval '.spec.ref.branch' k8s/platform-charts/01_fluxcd/templates/git-repo.yaml)
          if [ "$branch" != "main" ]; then
            echo "Error: .spec.ref.branch is \"$branch\", expected \"main\" in file k8s/platform-charts/01_fluxcd/templates/git-repo.yaml"
            exit 1
          fi
